kind: Template
apiVersion: v1
metadata:
  name: pims-db-deployment-template
  annotations:
    openshift.io/display-name: Microsoft SQL Server
    description: Relational database management system developed by Microsoft.
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}
      annotations:
        description: Exposes the database server
      labels:
        app: ${APP_NAME}
        component: ${COMP_NAME}
        env: ${ENV_NAME}
        role: database
    spec:
      ports:
        - name: 1433-tcp
          protocol: TCP
          port: 1433
          targetPort: 1433
      selector:
        name: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}
      type: ClusterIP
      sessionAffinity: None
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}
      annotations:
        description: Defines how to deploy the database server
      labels:
        app: ${APP_NAME}
        component: ${COMP_NAME}
        env: ${ENV_NAME}
        role: database
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${APP_NAME}-${COMP_NAME}-${ENV_NAME}
            from:
              kind: ImageStreamTag
              namespace: "${PROJECT_NAMESPACE}-tools"
              name: ${SQL_SERVER_RUNTIME_IMAGE}
      replicas: 1
      selector:
        name: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}
      template:
        metadata:
          name: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}
          labels:
            name: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}
            app: ${APP_NAME}
            component: ${COMP_NAME}
            env: ${ENV_NAME}
            role: database
        spec:
          volumes:
            - name: mssql-data
              persistentVolumeClaim:
                claimName: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}-data
          containers:
            - name: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}
              image: ""
              ports:
                - containerPort: 1433
                  protocol: TCP
              env:
                - name: ACCEPT_EULA
                  value: "Y"
                - name: MSSQL_SA_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}-secret
                      key: MSSQL_SA_PASSWORD
              resources:
                limits:
                  memory: ${MEMORY_LIMIT}
              volumeMounts:
                - mountPath: /var/opt/mssql
                  name: mssql-data
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}-data
      labels:
        app: ${APP_NAME}
        component: ${COMP_NAME}
        env: ${ENV_NAME}
        role: database
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: ${VOLUME_CAPACITY}
parameters:
  - name: APP_NAME
    displayName: App Name
    description: The name of the application (grouped).
    required: true
    value: pims
  - name: COMP_NAME
    displayName: Component Name
    description: The name of the application component [app, api, db]
    required: true
    value: db
  - name: ENV_NAME
    displayName: Environment name
    description: The name for this environment [dev, test, prod]
    required: true
    value: dev
  - name: PROJECT_NAMESPACE
    displayName: OpenShift Project Namespace
    description:
      The namespace of the OpenShift project containing the application.
    required: true
    value: jcxjin
  - name: SQL_SERVER_RUNTIME_IMAGE
    displayName: Microsoft SQL Server image
    description: The Microsoft SQL Server image tag.
    required: true
    value: mssql-rhel-server:2019-latest
  - name: MEMORY_LIMIT
    displayName: Memory Limit
    description: Maximum amount of memory the container can use.
    required: true
    value: 4Gi
  - name: VOLUME_CAPACITY
    displayName: Persistent Volume Capacity
    description: Volume space available for data, e.g. 512Mi, 2Gi
    value: 5Gi
    required: true
