apiVersion: v1
kind: Template
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}-sso-secret
      labels:
        app: ${APP_NAME}
        component: ${COMP_NAME}
        env: ${ENV_NAME}
        role: backend
    type: Opaque
    stringData:
      KEYCLOAK_AUTHORITY: ${KEYCLOAK_AUTHORITY}
      KEYCLOAK_AUDIENCE: ${KEYCLOAK_AUDIENCE}
      KEYCLOAK_SECRET: ${KEYCLOAK_SECRET}
parameters:
  - name: APP_NAME
    displayName: App Name
    description: The name of the application (grouped).
    required: true
    value: pims
  - name: COMP_NAME
    displayName: Component Name
    description: The name of the application component (e.g ui, backend, database).
    required: true
    value: api
  - name: ENV_NAME
    displayName: Environment name
    description: The name for this environment [dev, test, prod]
    required: true
    value: dev
  - name: KEYCLOAK_AUTHORITY
    displayName: Keycloak SSO realm
    description: Keycloak SSO bearer authority, used by the API server.  Eg, https://sso-dev.pathfinder.gov.bc.ca/auth/realms/<realm>
    required: true
    value: "https://sso-dev.pathfinder.gov.bc.ca/auth/realms/xz0xtue5"
  - name: KEYCLOAK_AUDIENCE
    displayName: Keycloak SSO audience
    description: Keycloak SSO bearer client ID, used by the API server
    required: true
    value: "pims-api"
  - name: KEYCLOAK_SECRET
    displayName: Keycloak SSO client secret (can be left blank for now)
    description: Keycloak secret key for the client.
    value: ""

