apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: param-has-value
spec:
  params:
    - name: VALUE
      description: A value to test if it has been set.
      type: string
  check:
    image: alpine
    script: |
      if [ -z "$(params.VALUE)" ]; then
        exit 1
      fi
