apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: param-is-true
spec:
  params:
    - name: VALUE
      description: A value to test if it has been set to 'true'.
      type: string
  check:
    image: alpine
    script: |
      if [ "$(params.VALUE)" != "true" ]; then
        exit 1
      fi
