kind: Template
apiVersion: v1
metadata:
  name: pims-api-unittest
  annotations:
    openshift.io/display-name: .NET Core build image to run tests
    description: Build template for a .NET Core image to run tests
    tags: pims-api
labels:
  app: pims
  component: api
  role: backend
objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${COMP_NAME}-unittest
      annotations:
        description: Defines how to build the application
    labels:
      name: ${APP_NAME}-${COMP_NAME}-unittest
      app: ${APP_NAME}
      component: ${COMP_NAME}
    spec:
      runPolicy: Parallel
      completionDeadlineSeconds: 1800
      triggers:
        - type: ImageChange
        - type: ConfigChange
      source:
        type: Git
        git:
          uri: "${GIT_REPO_URL}"
          ref: "${GIT_REF}"
        contextDir: "${SOURCE_CONTEXT_DIR}"
      strategy:
        type: Source
        sourceStrategy:
          env:
            - name: DOTNET_CONFIGURATION
              value: ${DOTNET_CONFIGURATION}
            - name: DOTNET_TEST_PROJECTS
              value: ${DOTNET_TEST_PROJECTS}
            - name: DOTNET_PUBLISH_READYTORUN
              value: ${DOTNET_PUBLISH_READYTORUN}
            - name: DOTNET_STARTUP_PROJECT
              value: ${DOTNET_STARTUP_PROJECT}
          from:
            kind: ImageStreamTag
            namespace: ${BUILDIMAGE_NAMESPACE}
            name: ${BUILDIMAGE_NAME}:${BUILDIMAGE_TAG}
          incremental: false
      output:
      postCommit:
        script: dotnet test
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
parameters:
  - name: APP_NAME
    displayName: App Name
    description: The name of the application (grouped).
    required: true
    value: "pims"
  - name: COMP_NAME
    displayName: Component Name
    description: The name of the application component.
    required: true
    value: "api"
  - name: BUILDIMAGE_NAMESPACE
    displayName: Source Image Namespace
    description: The s2i image namespace which is used to build the code.
    value: "jcxjin-tools"
  - name: BUILDIMAGE_NAME
    displayName: Source Image Name
    description: The image to use as the Builder Image.
    value: "dotnet-31-rhel7"
  - name: BUILDIMAGE_TAG
    displayName: Source Image Tag
    description: The s2i image tag which is used to build the code.
    value: "3.1"
  - name: GIT_REPO_URL
    displayName: GIT Source Repo URL
    description: A GIT URL to your source code.
    required: true
    value: https://github.com/bcgov/PIMS.git
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: dev
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: false
    value: backend
  - name: DOTNET_STARTUP_PROJECT
    displayName: Startup Project
    description:
      Set this to a project file (e.g. csproj) or a folder containing a single
      project file.
    required: true
    value: api/Pims.Api.csproj
  - name: DOTNET_PUBLISH_READYTORUN
    displayName: Ahead-of-time compilation
    description: Set this to 'true' to perform an ahead-of-time compilation.
    value: "true"
  - name: DOTNET_CONFIGURATION
    displayName: Configuration
    description: Set this to configuration (Release/Debug).
    value: "Release"
  - name: DOTNET_TEST_PROJECTS
    displayName: Test projects
    description: Set this to a space separated list of test projects to run before publishing.
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    value: "1"
  - name: MEMORY_LIMIT
    displayName: Memory Limit
    description: Maximum amount of memory the container can use.
    value: "6Gi"
