kind: Template
apiVersion: v1
metadata:
  name: nginx-build
  annotations:
    openshift.io/display-name: Nginx Image
    description: Build an image containing Nginx.
    tags: nginx

parameters:
  - name: SOLUTION_NAME
    displayName: Solution Group Name
    description: The name of the solution (e.g pims).
    required: true
    value: pims
  - name: APP_NAME
    displayName: Application Name
    description: The name of the application (e.g. nginx).
    required: true
    value: nginx

  - name: GIT_SOURCE
    displayName: Git Source Identifier
    description: A way to identify different sources (i.e. "dev" or "jmf")
    required: true
    value: dev
  - name: GIT_URL
    displayName: Git Repository URL
    description: The URL of the repository with your application source code.
    required: true
    value: https://github.com/bcgov/pims.git
  - name: GIT_REF
    displayName: Git Reference
    description:
      Set this to a branch name, tag or other ref of your repository if you
      are not using the default branch.
    value: dev
  - name: CONTEXT_DIR
    displayName: Context Directory
    description: Set this to use a subdirectory of the source code repository
    value: nginx
  - name: DOCKERFILE
    displayName: Dockerfile Name
    description: The Dockerfile name
    required: true
    value: Dockerfile.maintenance

  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: latest

  - name: CPU_REQUEST
    displayName: Requested Minimum Resources CPU Limit
    description: The requested minimum resources CPU limit (in cores) for this build.
    required: true
    value: 20m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 100m
  - name: MEMORY_REQUEST
    displayName: Requested Minimum Memory Limit
    description: Minimum requested amount of memory the container can use.
    required: true
    value: 100Mi
  - name: MEMORY_LIMIT
    displayName: Memory Limit
    description: Maximum amount of memory the container can use.
    required: true
    value: 1Gi

objects:
  # The final build image.
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${SOLUTION_NAME}-${APP_NAME}
      annotations:
        description: Destination for built images.
      labels:
        name: ${SOLUTION_NAME}-${APP_NAME}
        solution: ${SOLUTION_NAME}
        app: ${APP_NAME}

  # The build config that will be created will be named for the branch you created it for.
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${SOLUTION_NAME}-${APP_NAME}.${GIT_SOURCE}
      annotations:
        description: Build image from Dockerfile in git repo.
      labels:
        name: ${SOLUTION_NAME}-${APP_NAME}.${GIT_SOURCE}
        solution: ${SOLUTION_NAME}
        app: ${APP_NAME}
        branch: ${GIT_REF}
    spec:
      completionDeadlineSeconds: 1800
      triggers:
        - type: ImageChange
        - type: ConfigChange
      runPolicy: Serial
      source:
        git:
          uri: ${GIT_URL}
          ref: ${GIT_REF}
        contextDir: ${CONTEXT_DIR}
      strategy:
        type: Docker
        dockerStrategy:
          imageOptimizationPolicy: SkipLayers
          dockerfilePath: ${DOCKERFILE}
      output:
        to:
          kind: ImageStreamTag
          name: ${SOLUTION_NAME}-${APP_NAME}:${OUTPUT_IMAGE_TAG}
      resources:
        requests:
          cpu: ${CPU_REQUEST}
          memory: ${MEMORY_REQUEST}
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
