apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: api-editor-deploy
  annotations:
    description: Editor API application deployment configuration
    openshift.io/display-name: Editor API Application Deployment Configuration
    openshift.io/long-description: Deployment configuriation to Editor API application.
    tags: api,java,maven,editor

parameters:
  - name: SOLUTION_NAME
    displayName: Solution Group Name
    description: The name of the solution (e.g pims).
    required: true
    value: pims
  - name: APP_NAME
    displayName: Application Name
    description: The name of the application.
    required: true
    value: nginx

  - name: PROJECT_NAMESPACE
    displayName: OpenShift Project Namespace
    description: The namespace of the OpenShift project containing the application.
    required: true
    value: '354028'
  - name: ENV_NAME
    displayName: Environment name
    description: The name for this environment [dev, test, prod]
    required: true
    value: dev

  - name: IMAGE_TAG
    displayName: Image Tag
    description: The image tag that identifies which image to run. (i.e. 'dev').
    value: dev

  - name: APP_PORT
    displayName: Application Port
    description: The port used to communicate with the Pod
    value: '8080'

  - name: REPLICAS
    displayName: Pod Replicas
    description: Number of pod replicas to run
    value: '1'
  - name: CPU_REQUEST
    displayName: Requested Minimum Resources CPU Limit
    description: The requested minimum resources CPU limit (in cores) for this build.
    required: true
    value: 20m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 50m
  - name: MEMORY_REQUEST
    displayName: Requested Minimum Memory Limit
    description: Minimum requested amount of memory the container can use.
    required: true
    value: 50Mi
  - name: MEMORY_LIMIT
    displayName: Memory Limit
    description: Maximum amount of memory the container can use.
    required: true
    value: 100Mi

objects:
  # Open up ports to communicate with the app.
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${SOLUTION_NAME}-${APP_NAME}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: Exposes and load balances the application pods.
      labels:
        name: ${SOLUTION_NAME}-${APP_NAME}
        solution: ${SOLUTION_NAME}
        app: ${APP_NAME}
    spec:
      ports:
        - name: ${APP_PORT}-tcp
          port: ${{APP_PORT}}
          protocol: TCP
          targetPort: ${{APP_PORT}}
      selector:
        solution: ${SOLUTION_NAME}
        app: ${APP_NAME}
      sessionAffinity: None
      type: ClusterIP

  # How the app will be deployed to the pod.
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${SOLUTION_NAME}-${APP_NAME}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: Defines how to deploy ${SOLUTION_NAME}-${APP_NAME}
      labels:
        name: ${SOLUTION_NAME}-${APP_NAME}
        solution: ${SOLUTION_NAME}
        app: ${APP_NAME}
    spec:
      replicas: ${{REPLICAS}}
      selector:
        name: ${SOLUTION_NAME}-${APP_NAME}
        solution: ${SOLUTION_NAME}
        app: ${APP_NAME}
      strategy:
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          name: ${SOLUTION_NAME}-${APP_NAME}
          labels:
            name: ${SOLUTION_NAME}-${APP_NAME}
            solution: ${SOLUTION_NAME}
            app: ${APP_NAME}
        spec:
          containers:
            - name: ${SOLUTION_NAME}-${APP_NAME}
              image: ''
              imagePullPolicy: Always
              ports:
                - containerPort: ${{APP_PORT}}
                  protocol: TCP
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              # livenessProbe:
              #   httpGet:
              #     path: '/nginx-status'
              #     port: ${{APP_PORT}}
              #     scheme: HTTP
              #   initialDelaySeconds: 120
              #   timeoutSeconds: 60
              #   periodSeconds: 30
              #   successThreshold: 1
              #   failureThreshold: 3
              # readinessProbe:
              #   httpGet:
              #     path: '/nginx-status'
              #     port: ${{APP_PORT}}
              #     scheme: HTTP
              #   initialDelaySeconds: 120
              #   timeoutSeconds: 60
              #   periodSeconds: 30
              #   successThreshold: 1
              #   failureThreshold: 3
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${SOLUTION_NAME}-${APP_NAME}
            from:
              kind: ImageStreamTag
              namespace: ${PROJECT_NAMESPACE}-tools
              name: ${SOLUTION_NAME}-${APP_NAME}:${IMAGE_TAG}
