apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: app-editor-route
  annotations:
    description: Editor web application route
    openshift.io/display-name: Editor Web Application Route
    openshift.io/long-description: Route to Editor web application.
    tags: app,react,nginx,editor

parameters:
  - name: SOLUTION_NAME
    displayName: Solution Group Name
    description: The name of the solution (e.g pims).
    required: true
    value: pims
  - name: APP_NAME
    displayName: Application Name
    description: The name of the application.
    required: true
    value: nginx

  - name: PROJECT_NAMESPACE
    displayName: OpenShift Project Namespace
    description: The namespace of the OpenShift project containing the application.
    required: true
    value: '354028'
  - name: ENV_NAME
    displayName: Environment name
    description: The name for this environment [dev, test, prod]
    required: true
    value: dev

  - name: APP_HOST
    displayName: Application Hostname
    description: The exposed hostname that will route to the the React frontend, if left blank a value will be defaulted.
    value: pims-dev-nginx.apps.silver.devops.gov.bc.ca
  - name: APP_PATH
    displayName: Application URL Root Path
    description: The URL root path to the web application
    value: ''
  - name: APP_PORT
    displayName: Application Port
    description: The port used to communicate with the Pod
    value: '8080'

objects:
  # The route for the app.
  - kind: Route
    apiVersion: v1
    metadata:
      name: ${SOLUTION_NAME}-${APP_NAME}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      labels:
        name: ${SOLUTION_NAME}-${APP_NAME}
        solution: ${SOLUTION_NAME}
        app: ${APP_NAME}
    spec:
      host: ${APP_HOST}
      path: ${APP_PATH}
      port:
        targetPort: ${APP_PORT}-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
        # caCertificate: ""
        # certificate: ""
        # key: ""
      to:
        kind: Service
        name: ${SOLUTION_NAME}-${APP_NAME}
        weight: 100
