kind: Template
apiVersion: v1
metadata:
  name: ${COMP_NAME}-build-template
  annotations:
    openshift.io/display-name: .NET Core 3.1 Build Template
    description: Build template for a .NET Core 3.1 application.
    tags: ${COMP_NAME}
labels:
  name: ${COMP_NAME}-${SUFFIX}
  app: ${APP_NAME}
  role: backend
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${COMP_NAME}
      annotations:
        description: Keeps track of changes in the application image
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${COMP_NAME}-${SUFFIX}
      annotations:
        description: Defines how to build the application
    spec:
      triggers:
        - type: ImageChange
        - type: ConfigChange
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: ${GIT_REPO_URL}
          ref: ${GIT_REF}
        contextDir: ${SOURCE_CONTEXT_DIR}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: ${DOTNET_BUILDER_IMAGE}
          env:
            - name: DOTNET_STARTUP_PROJECT
              value: ${DOTNET_STARTUP_PROJECT}
      output:
        to:
          kind: ImageStreamTag
          name: ${COMP_NAME}:latest
      resources:
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
parameters:
  - name: APP_NAME
    displayName: App Name
    description: The name of the application (grouped).
    required: true
    value: pims
  - name: COMP_NAME
    displayName: Component Name
    description: The name of the application component (e.g ui, backend, database).
    required: true
    value: pims-api
  - name: SUFFIX
    displayName: Name Suffix
    description: A suffix appended to all objects; e.g. '-prod' or '-dev' or '-pr123'
    required: true
    value: dev
  - name: GIT_REPO_URL
    displayName: Git Repository URL
    description: The URL of the repository with your application source code.
    required: true
    value: https://github.com/bcgov/PIMS.git
  - name: GIT_REF
    displayName: Git Reference
    description:
      Set this to a branch name, tag or other ref of your repository if you
      are not using the default branch.
    value: dev
  - name: SOURCE_CONTEXT_DIR
    displayName: Context Directory
    description: Set this to use a subdirectory of the source code repository
    value: backend
  - name: DOTNET_BUILDER_IMAGE
    displayName: .NET builder
    description: The s2i image which is used to build the code.
    required: true
    value: dotnet-31-rhel7:3.1
  - name: DOTNET_STARTUP_PROJECT
    displayName: Startup Project
    description:
      Set this to a project file (e.g. csproj) or a folder containing a single
      project file.
    required: true
    value: BackendApi.csproj
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: "1"
  - name: MEMORY_LIMIT
    displayName: Memory Limit
    description: Maximum amount of memory the container can use.
    required: true
    value: 6Gi
