kind: Template
apiVersion: v1
metadata:
  name: nodejs16-image-stream
  annotations:
    openshift.io/display-name: NodeJS 16 Redhat Image
    description: ImageStream definitions for NodeJS 16 on RHEL8
parameters:
  - name: IMAGE_NAME
    displayName: "The name of this image"
    required: true
    value: "nodejs-16"
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${IMAGE_NAME}
    spec:
      tags:
        - name: "1-68.1666660386"
          from:
            kind: DockerImage
            name: "registry.redhat.io/rhel8/nodejs-16:1-68.1666660386"
          referencePolicy:
            type: Local
