kind: Template
apiVersion: v1
metadata:
  name: nodejs-image-stream
  annotations:
    openshift.io/display-name: NodeJS 10 Redhat Image
    description: ImageStream definitions for NodeJS 10 on RHEL
parameters:
  - name: IMAGE_NAME
    displayName: "The name of this image"
    required: true
    value: "nodejs-10-rhel7"
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${IMAGE_NAME}
    spec:
      tags:
        - name: "1-30"
          from:
            kind: DockerImage
            name: "registry.redhat.io/rhscl/nodejs-10-rhel7:1-30"
          referencePolicy:
            type: Local
