kind: Template
apiVersion: v1
metadata:
  name: git-triggered-pipeline
  annotations:
    openshift.io/display-name: GIT Triggered Pipeline
    description:
      Listen for a GIT merge event to trigger a pipeline run.
    tags: git,trigger,tekton

parameters:
  - name: SOLUTION_NAME
    displayName: Solution Name
    description: The name of the solution.
    required: true
    value: pims
  - name: APP_NAME
    displayName: Application Name
    description: The name of the application.
    required: true
    value: app

objects:
  # Create a pipeline run object.
  - apiVersion: triggers.tekton.dev/v1alpha1
    kind: TriggerTemplate
    metadata:
      name: git-${SOLUTION_NAME}-${APP_NAME}
      solution: ${SOLUTION_NAME}
      app: ${APP_NAME}
    spec:
      params:
        - name: GIT_SOURCE
          description: Identify the git source
        - name: VERSION
          description: The version to tag the image with
        - name: DEPLOY_TO
          description: The environment to depoloy to
      resourcetemplates:
        - apiVersion: tekton.dev/v1beta1
          kind: PipelineRun
          metadata:
            generateName: ${SOLUTION_NAME}-${APP_NAME}-$(tt.params.VERSION)-
            labels:
              name: ${SOLUTION_NAME}-${APP_NAME}-$(tt.params.VERSION)
              solution: ${SOLUTION_NAME}
              app: ${APP_NAME}
              version: $(tt.params.VERSION)
              tekton.dev/pipeline: ${SOLUTION_NAME}-pipeline
          spec:
            pipelineRef:
              name: ${SOLUTION_NAME}-pipeline
            serviceAccountName: pipeline
            timeout: 0h45m0s
            params:
              - name: GIT_SOURCE
                value: $(tt.params.GIT_SOURCE)
              - name: IMAGE_TAG
                value: $(tt.params.VERSION)
              - name: DEPLOY_TO
                value: $(tt.params.DEPLOY_TO)
            workspaces:
              - name: owasp-settings
                emptyDir: {}
