kind: Template
apiVersion: v1
metadata:
  name: github-webhook-ingress
  annotations:
    openshift.io/display-name: GitHub WebHook Ingress
    description: Ingress object to enable git webhook
    tags: webhook
parameters:
  - name: SOLUTION_NAME
    displayName: Solution Name
    description: The name of the solution.
    required: true
    value: pims
  - name: APP_NAME_1
    displayName: Application Name
    description: The name of the application event listening trigger.
    required: true
    value: api
  - name: APP_NAME_2
    displayName: Application Name
    description: The name of the application event listening trigger.
    required: true
    value: app
objects:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: git-webhook-${SOLUTION_NAME}
      solution: ${SOLUTION_NAME}
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
    spec:
      rules:
        - host: ${SOLUTION_NAME}-tekton.apps.silver.devops.gov.bc.ca
          http:
            paths:
              - path: /hooks/${APP_NAME_1}
                pathType: Exact
                backend:
                  service:
                    name: el-git-${SOLUTION_NAME}-${APP_NAME_1}
                    port:
                      number: 8080
              - path: /hooks/${APP_NAME_2}
                pathType: Exact
                backend:
                  service:
                    name: el-git-${SOLUTION_NAME}-${APP_NAME_2}
                    port:
                      number: 8080
