kind: Template
apiVersion: v1
metadata:
  name: github-webhook
  annotations:
    openshift.io/display-name: GitHub Webhook
    description: GitHub webhook secret
    tags: webhook
parameters:
  - name: SOLUTION_NAME
    displayName: App Name
    description: The name of the application (grouped).
    required: true
    value: pims
  - name: APP_NAME
    displayName: Component Group Name
    description: The name of the application component group [app, api, database]
    required: true
    value: webhook

  - name: WEBHOOK_SECRET
    displayName: GitHub Webhook Secret
    description: The secret that will be used by the GitHub webhook
    from: "[a-zA-Z0-9]{5}-[a-zA-Z0-9]{5}-[a-zA-Z0-9]{5}-[a-zA-Z0-9]{5}-[a-zA-Z0-9]{5}"
    generate: expression
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${SOLUTION_NAME}-${APP_NAME}
      annotations:
        description: "GitHub webhook secret"
      labels:
        name: ${SOLUTION_NAME}-${APP_NAME}
        solution: ${SOLUTION_NAME}
        app: ${APP_NAME}
    type: Opaque
    stringData:
      webhook: ${WEBHOOK_SECRET}
