version: '2'

checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 25
  file-lines:
    enabled: false
  method-complexity:
    enabled: true
    config:
      threshold: 25
  method-count:
    enabled: true
    config:
      threshold: 50
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: true

exclude_patterns:
  - '**/dist/'
  - '**/node_modules/'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/tests/'
  - '**/Migrations/'
  - '**/*.d.ts'
  - '**/cypress/'
  - '**/test/'
  - '**/testUtils.ts'
  - 'tools/'
  - '.github/'
  - '**/.vscode/'
  - 'adr/'
  - '**/coverage/'
  - '**/public/'
  - '**/__mocks__/'
  - '**/constants/'
  - '**/interfaces/'
  - '**/types/'
  - '**/typings/'
  - 'scripts/'
  - 'Screenshots/'
