version: "3.5"

services:
  ####################### Keycloak #######################
  keycloak-db:
    container_name: keycloak-db
    build:
      context: ./auth/postgres
    ports:
      - "5432:5432"
    env_file:
      - auth/.env
    volumes:
      - keycloak-db-data:/var/lib/pgsql/data
    networks:
      - pims

  keycloak:
    container_name: keycloak
    build:
      context: ./auth/keycloak
    env_file:
      - auth/.env
    volumes:
      - ./auth/keycloak/config:/tmp
    ports:
      - 8080:8080
    depends_on:
      - keycloak-db
    networks:
      - pims

  ####################### Database #######################
  database:
    restart: always
    container_name: api-db
    build:
      context: database/mssql
    env_file:
      - database/.env
    ports:
      - "5433:1433"
    volumes:
      - api-db-data:/var/opt/mssql
    networks:
      - pims

  ####################### Backend #######################
  backend:
    restart: always
    container_name: backend-api
    build:
      context: backend
    env_file: backend/.env
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - database
      - keycloak
    # volumes:
    #   - $(AppData)/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - pims

  ####################### Frontend #######################
  frontend:
    restart: always
    container_name: frontend-app
    build:
      context: frontend
    volumes:
      - ./frontend/src/:/usr/app/src/
      - frontend-node-cache:/usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file: ./frontend/.env
    environment:
      - NODE_ENV=development
      - KEYCLOAK_URL=http://host.docker.internal:8080/auth/admin/realms/quartech/users
      - CHOKIDAR_USEPOLLING=true
    networks:
      - pims

  ####################### Local SMTP Server #######################
  # mailhog:
  #   container_name: mailhog
  #   restart: always
  #   image: mailhog/mailhog:latest
  #   ports:
  #     - 25:1025
  #     - 1025:1025
  #     - 8025:8025 # visit localhost:8025 to see the list of captured emails
  #   networks:
  #     - starter_kit

####################### Networks Definition #######################
networks:
  pims:
    name: pims-net
    driver: bridge

####################### Volumes Definition #######################
volumes:
  api-db-data:
  frontend-node-cache:
  keycloak-db-data:
