version: "3.5"

services:
  ####################### Keycloak #######################
  keycloak-db:
    restart: on-failure
    container_name: keycloak-db
    build:
      context: ./auth/postgres
    ports:
      - "5432:5432"
    env_file:
      - auth/postgres/.env
    volumes:
      - keycloak-db-data:/var/lib/pgsql/data
    networks:
      - pims

  keycloak:
    restart: on-failure
    container_name: keycloak
    build:
      context: ./auth/keycloak
    env_file:
      - auth/keycloak/.env
    volumes:
      - ./auth/keycloak/config:/tmp
    ports:
      - 8080:8080
    depends_on:
      - keycloak-db
    networks:
      - pims

  ####################### Database #######################
  database:
    restart: on-failure
    container_name: api-db
    build:
      context: database/mssql
    env_file:
      - database/mssql/.env
    ports:
      - "5433:1433"
    volumes:
      - api-db-data:/var/opt/mssql
    networks:
      - pims

  ####################### Backend #######################
  backend:
    restart: on-failure
    container_name: backend-api
    build:
      context: backend
      args:
        BUILD_CONFIGURATION: Debug
    env_file: backend/api/.env
    ports:
      - "5001:443"
      - "5000:8080"
    depends_on:
      - database
      - keycloak
    networks:
      - pims

  ####################### Frontend #######################
  frontend:
    stdin_open: true
    tty: true
    restart: on-failure
    container_name: frontend-app
    build:
      context: frontend
    volumes:
      - ./frontend/src:/usr/app/src
      - ./frontend/public:/usr/app/public
      - frontend-node-cache:/usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file: ./frontend/.env
    networks:
      - pims

####################### Networks Definition #######################
networks:
  pims:
    name: pims-net
    driver: bridge

####################### Volumes Definition #######################
volumes:
  api-db-data:
  frontend-node-cache:
  keycloak-db-data:
