services:
  ####################### Database #######################
  database:
    profiles: ['prod', 'dev']
    restart: 'no'
    container_name: pims-database
    build:
      context: database/mssql
    env_file:
      - database/mssql/.env
    ports:
      - ${DATABASE_PORT:-5433}:1433
    volumes:
      - database-data:/var/opt/mssql/data
    networks:
      - pims

  ####################### Backend #######################
  backend:
    profiles: ['prod', 'dev']
    restart: 'no'
    container_name: pims-api
    build:
      context: backend
      args:
        BUILD_CONFIGURATION: Debug
    env_file: backend/api/.env
    ports:
      - ${API_HTTPS_PORT:-5001}:443
      - ${API_HTTP_PORT:-5000}:8080
    depends_on:
      - database
    networks:
      - pims

  ####################### Frontend #######################
  frontend:
    profiles: ['prod']
    stdin_open: true
    tty: true
    restart: 'no'
    container_name: pims-app
    build:
      context: frontend
      target: prod
      dockerfile: Dockerfile
    ports:
      - ${APP_HTTP_PORT:-3000}:3000
    depends_on:
      - backend
    env_file: .env
    networks:
      - pims

  ####################### Frontend Dev #######################
  frontend-dev:
    profiles: ['dev']
    stdin_open: true
    tty: true
    restart: 'no'
    container_name: pims-app-dev
    build:
      context: frontend
      target: dev
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - pims-app-node-cache:/app/node_modules
    ports:
      - ${APP_HTTP_PORT:-3000}:3000
    depends_on:
      - backend
    env_file: .env
    networks:
      - pims

####################### Networks Definition #######################
networks:
  pims:
    name: pims-net
    driver: bridge

####################### Volumes Definition #######################
volumes:
  database-data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/database/mssql/data
      o: bind
  pims-app-node-cache:
    name: pims-app-node-cache
