services:
  ####################### Keycloak #######################
  keycloak:
    restart: 'no'
    container_name: pims-keycloak
    build:
      context: ./auth/keycloak
    env_file:
      - auth/keycloak/.env
    volumes:
      - ./auth/keycloak/config/realm-export.json:/tmp/realm-export.json
    ports:
      - ${KEYCLOAK_PORT:-8080}:8080
    networks:
      - pims

  ####################### Database #######################
  database:
    restart: 'no'
    container_name: pims-database
    build:
      context: database/mssql
    env_file:
      - database/mssql/.env
    ports:
      - ${DATABASE_PORT:-5433}:1433
    volumes:
      - database-data:/var/opt/mssql/data
    networks:
      - pims

  ####################### Backend #######################
  backend:
    restart: 'no'
    container_name: pims-api
    build:
      context: backend
      args:
        BUILD_CONFIGURATION: Debug
    env_file: backend/api/.env
    ports:
      - ${API_HTTPS_PORT:-5001}:443
      - ${API_HTTP_PORT:-5000}:8080
    depends_on:
      - database
      - keycloak
    networks:
      - pims

  ####################### Frontend #######################
  frontend:
    stdin_open: true
    tty: true
    restart: 'no'
    container_name: pims-app
    build:
      context: frontend
    volumes:
      - ./frontend/src:/usr/app/src
      - ./frontend/public:/usr/app/public
      - pims-app-node-cache:/usr/app/node_modules
    ports:
      - ${APP_HTTP_PORT:-3000}:3000
    depends_on:
      - backend
    env_file: ./frontend/.env
    networks:
      - pims

####################### Networks Definition #######################
networks:
  pims:
    name: pims-net
    driver: bridge

####################### Volumes Definition #######################
volumes:
  database-data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/database/mssql/data
      o: bind
  pims-app-node-cache:
    name: pims-app-node-cache
