FROM mcr.microsoft.com/dotnet/core/sdk:3.1

ENV DOTNET_CLI_HOME=/tmp
ENV PATH="$PATH:/tmp/.dotnet/tools"

# Switch to root for package installs
USER 0
RUN dotnet tool install --global dotnet-ef

WORKDIR /src
COPY . .
RUN fix_permissions() { while [ $# -gt 0 ] ; do chgrp -R 0 "$1" && chmod -R g=u "$1"; shift; done } && \
    fix_permissions "/src" "/tmp"

# Run container by default as user with id 1001 (default)
USER 1001

ENTRYPOINT cd /src/dal && dotnet ef database update -v
