---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: file-storage
  labels:
    name: app
    part-of: pims
    version: 1.0.0
    component: app
    created-by: jeremy.foster
spec:
  # Storage class name is the type of storage [netapp-file-standard, netapp-file-extended, netapp-file-backup, netapp-block-standard, netapp-block-extended]
  storageClassName: netapp-file-standard
  # Storage access mode [ReadWriteOnce, ReadWriteMany]
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
