kind: Template
apiVersion: v1
metadata:
  name: pims-migrations
parameters:
  - name: SOLUTION_NAME
    displayName: Solution Group Name
    description: The name of the solution (e.g pims).
    required: true
    value: pims
  - name: APP_NAME
    displayName: Application Name
    description: The name of the application (e.g. api).
    required: true
    value: migrations

  - name: GIT_SOURCE
    displayName: Git Source Identifier
    description: A way to identify different sources (i.e. "dev" or "jmf")
    required: true
    value: dev
  - name: GIT_URL
    displayName: Git Repo URL
    description:
      The URL to your GIT repo, don't use the this default unless your just
      experimenting.
    required: true
    value: https://github.com/bcgov/PIMS.git
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: dev
  - name: CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: true
    value: backend
  - name: DOCKERFILE_PATH
    displayName: Path to Dockerfile
    description: Path for alternate Dockerfile to use for build
    value: Dockerfile.migrations

  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: latest

  - name: CPU_REQUEST
    displayName: Requested Minimum Resources CPU Limit
    description: The requested minimum resources CPU limit (in cores) for this build.
    required: true
    value: 20m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 500m
  - name: MEMORY_REQUEST
    displayName: Requested Minimum Memory Limit
    description: Minimum requested amount of memory the container can use.
    required: true
    value: 250Mi
  - name: MEMORY_LIMIT
    displayName: Memory Limit
    description: Maximum amount of memory the container can use.
    required: true
    value: 2Gi
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${SOLUTION_NAME}-${APP_NAME}

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${SOLUTION_NAME}-${APP_NAME}.${GIT_SOURCE}
    spec:
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: ${GIT_URL}
          ref: ${GIT_REF}
        contextDir: ${CONTEXT_DIR}
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: ${DOCKERFILE_PATH}
      output:
        to:
          kind: ImageStreamTag
          name: ${SOLUTION_NAME}-${APP_NAME}:${OUTPUT_IMAGE_TAG}
      resources:
        requests:
          cpu: ${CPU_REQUEST}
          memory: ${MEMORY_REQUEST}
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
