kind: Template
apiVersion: v1
metadata:
  name: migration-job
parameters:
  - name: IMAGE
    displayName: Image Name
    description: Docker registry reference image.
    required: true
    value: pims-migrations
  - name: IMAGE_TAG
    displayName: Image Tag Name
    description: The image tag that will be used for this job.
    required: true
    value: dev
  - name: NAMESPACE
    description: Target namespace reference (i.e. 'jcxjin-tools')
    displayName: Namespace
    required: true
    value: jcxjin-tools
  - name: ENV_NAME
    displayName: Environment name
    description: The name for this environment [dev, test, prod]
    required: true
    value: dev
  - name: ASPNETCORE_ENVIRONMENT
    displayName: AspNetCore Environment
    description: The ASP Net Core deployment environment setting,
      [Development, Staging, Production].
    required: true
    value: Production
  - name: DATABASE_ROLE_NAME
    displayName: Database Role Name
    description: The name of the database service account role name (i.e. database).
    required: true
    value: "database"
  - name: ROLE_NAME
    displayName: "Component Name"
    description: "The name of the application role (e.g api, app, database)."
    required: true
    value: "migrations"
  - name: APP_NAME
    displayName: "App Name"
    description: "The name of the application (grouped)."
    required: true
    value: "pims"
objects:
  # Allow the migration pod to communicate with the database.
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: pod-from-pod-permit-${NAME}-${ROLE_NAME}-${DATABASE_ROLE_NAME}
    spec:
      #description: Allow migration pod(s) to receive communication from database pod(s).
      podSelector:
        matchLabels:
          app: ${APP_NAME}
          role: ${DATABASE_ROLE_NAME}
          env: ${ENV_NAME}
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  app: ${APP_NAME}
                  role: ${ROLE_NAME}
                  env: ${ENV_NAME}
  - kind: Pod
    apiVersion: v1
    metadata:
      generateName: migration-job-
    spec:
      restartPolicy: Never
      activeDeadlineSeconds: 900
      containers:
        - name: dotnet-ef
          image: docker-registry.default.svc:5000/${NAMESPACE}/${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: ${ASPNETCORE_ENVIRONMENT}
            - name: ConnectionStrings__PIMS
              valueFrom:
                configMapKeyRef:
                  name: pims-api-${ENV_NAME}-db-client
                  key: CONNECTION_STRINGS_PIMS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pims-db-${ENV_NAME}-secret
                  key: DB_PASSWORD
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500Mi
