apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    description: Defines how to deploy jenkins
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","metadata":{"annotations":{"description":"Defines
      how to deploy
      jenkins"},"labels":{"app":"jenkins","name":"jenkins"},"name":"jenkins","namespace":"jcxjin-tools"},"spec":{"replicas":1,"selector":{"app":"jenkins"},"strategy":{"type":"Rolling"},"template":{"metadata":{"labels":{"app":"jenkins","name":"jenkins"},"name":"jenkins"},"spec":{"containers":[{"env":[{"name":"OPENSHIFT_ENABLE_OAUTH","value":"true"},{"name":"OPENSHIFT_JENKINS_JVM_ARCH","value":"x86_64"}],"image":"","name":"jenkins","ports":[{"containerPort":8080,"protocol":"TCP"}]}]}},"triggers":[{"type":"ConfigChange"},{"imageChangeParams":{"automatic":true,"containerNames":["jenkins"],"from":{"kind":"ImageStreamTag","name":"jenkins-2-rhel7:latest","namespace":"jcxjin-tools"}},"type":"ImageChange"}]}}
  creationTimestamp: "2020-05-07T20:46:21Z"
  generation: 19
  labels:
    app: jenkins
    name: jenkins
  name: jenkins
  namespace: jcxjin-tools
  resourceVersion: "1772725797"
  selfLink: /apis/apps.openshift.io/v1/namespaces/jcxjin-tools/deploymentconfigs/jenkins
  uid: ceb58910-90a3-11ea-9ccd-0050568348cc
spec:
  replicas: 1
  selector:
    app: jenkins
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins
        name: jenkins
      name: jenkins
    spec:
      containers:
        - env:
            - name: OPENSHIFT_ENABLE_OAUTH
              value: "true"
            - name: OPENSHIFT_JENKINS_JVM_ARCH
              value: x86_64
            - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
              value: "true"
            - name: KUBERNETES_MASTER
              value: "https://kubernetes.default:443"
            - name: KUBERNETES_TRUST_CERTIFICATES
              value: "true"
            - name: JNLP_SERVICE_NAME
              value: jenkins-jnlp
            - name: JAVA_OPTS
              value: >-
                -XX:MaxMetaspaceSize=512m -Duser.timezone=America/Vancouver
                -Dhudson.model.DirectoryBrowserSupport.CSP=
          image: >-
            docker-registry.default.svc:5000/openshift/jenkins@sha256:36f8501570cd2846cc93f34a53010f3971803876bf11362399267fcd0368feb2
          imagePullPolicy: IfNotPresent
          name: jenkins
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/jenkins
              name: jenkins-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: jenkins
      serviceAccountName: jenkins
      terminationGracePeriodSeconds: 30
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-data
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - jenkins
        from:
          kind: ImageStreamTag
          name: "jenkins:2"
          namespace: openshift
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/openshift/jenkins@sha256:36f8501570cd2846cc93f34a53010f3971803876bf11362399267fcd0368feb2
      type: ImageChange
    - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2020-05-07T21:48:07Z"
      lastUpdateTime: "2020-05-07T21:48:07Z"
      message: replication controller "jenkins-8" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2020-05-07T21:48:24Z"
      lastUpdateTime: "2020-05-07T21:48:24Z"
      message: Deployment config has minimum availability.
      status: "True"
      type: Available
  details:
    causes:
      - type: ConfigChange
    message: config change
  latestVersion: 8
  observedGeneration: 19
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
