/* eslint-disable @typescript-eslint/no-duplicate-enum-values */
export enum WorkflowStatus {
  Draft = 'DR',
  SelectProperties = 'DR-P',
  UpdateInformation = 'DR-I',
  RequiredDocumentation = 'DR-D',
  Approval = 'DR-A',
  Review = 'DR-RE',
  PropertyReview = 'AS-I',
  DocumentReview = 'AS-D',
  AppraisalReview = 'AS-AP',
  FirstNationConsultation = 'AS-FNC',
  ExemptionReview = 'AS-EXE',
  ExemptionProcess = 'AS-EXP',
  ApprovedForErp = 'AP-ERP',
  OnHold = 'ERP-OH',
  ERP = 'ERP-ON',
  TransferredGRE = 'T-GRE',
  ApprovedForSpl = 'AP-SPL',
  PreMarketing = 'SPL-PM',
  OnMarket = 'SPL-M',
  ContractInPlaceConditional = 'SPL-CIP-C',
  ContractInPlaceUnconditional = 'SPL-CIP-U',
  NotInSpl = 'AP-!SPL',
  ApprovedForExemption = 'AP-EXE',
  Denied = 'DE',
  Disposed = 'DIS',
  Cancelled = 'CA',
  InErp = 'ERP-ON',
}
