kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: busybox
  namespace: 354028-dev
  annotations:
    description: A Busybox container to help debug the mapped volumes.
  labels:
    name: busybox
    env: dev
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    name: busybox
  template:
    metadata:
      name: busybox
      labels:
        name: busybox
        env: dev
    spec:
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: pims-database
        - name: backup
          persistentVolumeClaim:
            claimName: pims-database-backup
      containers:
        - name: busybox
          image: busybox:1.35.0
          args: ["tail", "-f", "/dev/null"]
          resources:
            limits:
              cpu: 250m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
            - name: backup
              mountPath: /backups
