kind: Template
apiVersion: v1
metadata:
  name: pims-db-deploy
  annotations:
    openshift.io/display-name: Microsoft SQL Server
    description: Relational database management system developed by Microsoft.
    tags: pims,db
parameters:
  - name: APP_NAME
    displayName: "App Name"
    description: "The name of the application (grouped)."
    required: true
    value: "pims"
  - name: ROLE_NAME
    displayName: "Component Role Name"
    description: "The name of the application component role [app, api, database]"
    required: true
    value: "database"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod]"
    required: true
    value: "dev"
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "354028"
  - name: INSTANCE
    displayName: "Unique Identifier"
    description: "A unique identifier to allow for multiple instances (i.e. '-01')."
    value: ""

  - name: IMAGE_TAG
    displayName: "Source Image Tag"
    description: "The tag given to the built image that will be deployed."
    required: true
    value: "latest"

  - name: MSSQL_PID
    displayName: "The Microsoft SQL Server Edition"
    description: "The edition of the database to run [Developer|Express|Standard|Enterprise|EnterpriseCore]"
    required: true
    value: "Developer"
  - name: MSSQL_SA_PASSWORD
    displayName: "Microsoft SQL Server Password"
    description: "Microsoft SQL Server sa password"
    from: '[\w]{5}_[\w]{15}_1aB!'
    generate: expression
  - name: MSSQL_PORT
    displayName: "The Database Port Number"
    description: "The Port that will be openned to the database (defaults to 1433)."
    required: true
    value: "1433"
  - name: TIMEZONE
    displayName: "Timezone"
    description: "The Timezone to run the database in (i.e. America/Los_Angeles)."
    required: true
    value: "America/Los_Angeles"
  - name: DB_NAME
    displayName: "Database Name"
    description: "The name of the PIMS database that will be created."
    required: true
    value: "pims"
  - name: DB_USER
    displayName: "Database Username"
    description: "The username to access the database from PIMS that will be created."
    required: true
    value: "admin"
  - name: DB_PASSWORD
    displayName: "Microsoft SQL Server Password"
    description: "Microsoft SQL Server sa password."
    from: '[\w]{12}_1Ab!'
    generate: expression

  - name: STORAGE_CLASS_NAME
    displayName: "The Storage Class Name"
    description: "The storage class name is the type of storage [netapp-file-standard, netapp-file-extended, netapp-file-backup, netapp-block-standard, netapp-block-extended]"
    required: true
    value: "netapp-file-standard"
  - name: ACCESS_MODE
    displayName: "The Storage Access Mode"
    description: "The storage access mode [ReadWriteOnce, ReadWriteMany]"
    required: true
    value: "ReadWriteMany"
  - name: VOLUME_CAPACITY
    displayName: "Persistent Volume Capacity"
    description: "Volume space available for data, e.g. 512Mi, 2Gi."
    required: true
    value: "5Gi"

  - name: BACKUP_ROLE_NAME
    displayName: "Backup Service Role Name"
    description: "The name of the application component role [app, api, database, backup]"
    required: true
    value: "backup"
  - name: BACKUP_STORAGE_CLASS_NAME
    displayName: "The Backup Storage Class Name"
    description: "The backup storage class name is the type of storage [netapp-file-standard, netapp-file-extended, netapp-file-backup, netapp-block-standard, netapp-block-extended]"
    required: true
    value: "netapp-file-backup"
  - name: BACKUP_ACCESS_MODE
    displayName: "The Backup Storage Access Mode"
    description: "The backup storage access mode [ReadWriteOnce, ReadWriteMany]"
    required: true
    value: "ReadWriteMany"
  - name: BACKUP_VOLUME_CAPACITY
    displayName: "Backup persistent Volume Capacity"
    description: "Backup bolume space available for data, e.g. 512Mi, 2Gi."
    required: true
    value: "5Gi"

  - name: CPU_REQUEST
    displayName: "Requested Minimum Resources CPU Limit"
    description: "The requested minimum resources CPU limit (in cores) for this build."
    required: true
    value: "100m"
  - name: CPU_LIMIT
    displayName: "Resources CPU Limit"
    description: "The resources CPU limit (in cores) for this build."
    required: true
    value: "2"
  - name: MEMORY_REQUEST
    displayName: "Requested Minimum Memory Limit"
    description: "Minimum requested amount of memory the container can use."
    required: true
    value: "500Mi"
  - name: MEMORY_LIMIT
    displayName: "Memory Limit"
    description: "Maximum amount of memory the container can use."
    required: true
    value: "4Gi"
objects:
  # Persistent storage for the database.
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      labels:
        name: ${APP_NAME}-database${INSTANCE}
        app: ${APP_NAME}
        env: ${ENV_NAME}
        role: ${ROLE_NAME}
    resourceVersion: "250191500"
    selfLink: /api/v1/namespaces/${PROJECT_NAMESPACE}-${ENV_NAME}/persistentvolumeclaims/${APP_NAME}-${ROLE_NAME}${INSTANCE}
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: csi.trident.netapp.io
      description: "${APP_NAME} Database storage volume"
    finalizers:
      - kubernetes.io/pvc-protection
    spec:
      accessModes:
        - ${ACCESS_MODE}
      resources:
        requests:
          storage: ${VOLUME_CAPACITY}
      storageClassName: ${STORAGE_CLASS_NAME}
      volumeMode: Filesystem

  # Storage for backup.
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}-${BACKUP_ROLE_NAME}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      labels:
        name: ${APP_NAME}-${ROLE_NAME}-${BACKUP_ROLE_NAME}
        app: ${APP_NAME}
        role: ${BACKUP_ROLE_NAME}
        env: ${ENV_NAME}
    spec:
      storageClassName: ${BACKUP_STORAGE_CLASS_NAME}
      accessModes:
        - ${BACKUP_ACCESS_MODE}
      resources:
        requests:
          storage: ${BACKUP_VOLUME_CAPACITY}

  # Add a resource secret for the database password.  By default this is generated.
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: "Database passwords"
      labels:
        name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
        app: ${APP_NAME}
        role: ${ROLE_NAME}
        env: ${ENV_NAME}
    type: Opaque
    stringData:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  # Expose the database port to the pod.
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: Exposes the database server
      labels:
        name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
        app: ${APP_NAME}
        role: ${ROLE_NAME}
        env: ${ENV_NAME}
    spec:
      ports:
        - name: ${MSSQL_PORT}-tcp
          protocol: TCP
          port: ${{MSSQL_PORT}}
          targetPort: ${{MSSQL_PORT}}
      selector:
        name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
      type: ClusterIP
      sessionAffinity: None

  # Configure how the database is deployed to the pod.
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: Defines how to deploy the database server
      labels:
        name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
        app: ${APP_NAME}
        role: ${ROLE_NAME}
        env: ${ENV_NAME}
    spec:
      strategy:
        type: Recreate
      recreateParams:
        pre: {}
        mid: {}
        post: {}
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${APP_NAME}-${ROLE_NAME}${INSTANCE}
            from:
              kind: ImageStreamTag
              namespace: "${PROJECT_NAMESPACE}-tools"
              name: ${APP_NAME}-${ROLE_NAME}:${IMAGE_TAG}
      replicas: 1
      selector:
        name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
      template:
        metadata:
          name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
          labels:
            name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
            app: ${APP_NAME}
            role: ${ROLE_NAME}
            env: ${ENV_NAME}
        spec:
          volumes:
            - name: mssql-data
              persistentVolumeClaim:
                claimName: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
            - name: backup
              persistentVolumeClaim:
                claimName: ${APP_NAME}-${ROLE_NAME}-${BACKUP_ROLE_NAME}
          containers:
            - name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
              image: ""
              ports:
                - containerPort: ${{MSSQL_PORT}}
                  protocol: TCP
              env:
                - name: ACCEPT_EULA
                  value: "Y"
                - name: MSSQL_PID
                  value: ${MSSQL_PID}
                - name: TZ
                  value: ${TIMEZONE}
                - name: MSSQL_SA_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
                      key: MSSQL_SA_PASSWORD
                - name: DB_NAME
                  value: ${DB_NAME}
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
                      key: DB_USER
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-${ROLE_NAME}${INSTANCE}
                      key: DB_PASSWORD
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
              volumeMounts:
                - name: mssql-data
                  mountPath: /var/opt/mssql
                - name: backup
                  mountPath: /backups
