apiVersion: v1
kind: Template
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}-health-secret
      labels:
        app: ${APP_NAME}
        component: ${COMP_NAME}
        env: ${ENV_NAME}
        role: backend
    type: Opaque
    stringData:
      HealthChecksUI__Webhooks__0__Uri: ${ROCKETCHAT_HEALTH_HOOK_URI}
parameters:
  - name: APP_NAME
    displayName: App Name
    description: The name of the application (grouped).
    required: true
    value: pims
  - name: COMP_NAME
    displayName: Component Name
    description: The name of the application component (e.g ui, backend, database).
    required: true
    value: api
  - name: ENV_NAME
    displayName: Environment name
    description: The name for this environment [dev, test, prod]
    required: true
    value: dev
  - name: ROCKETCHAT_HEALTH_HOOK_URI
    displayName: RocketChat webhook uri.
    description: RocketChat webhook uri that should be used to post health check messages.
    required: true
    value: ""
