apiVersion: v1
kind: Template
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${ENV_NAME}${ID}-sso-client
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: "Keycloak SSO client configuration"
      labels:
        name: ${APP_NAME}-${ENV_NAME}${ID}-sso-client
        app: ${APP_NAME}
        component: ${COMP_NAME}
        env: ${ENV_NAME}
        role: backend
        id: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}${ID}
    type: Opaque
    data:
      KEYCLOAK_AUDIENCE: ${KEYCLOAK_AUDIENCE}
      KEYCLOAK_AUTHORITY: ${KEYCLOAK_AUTHORITY}
      KEYCLOAK_ADMIN_AUTHORITY: ${KEYCLOAK_ADMIN_AUTHORITY}
parameters:
  - name: APP_NAME
    displayName: App Name
    description: The name of the application (grouped).
    required: true
    value: pims
  - name: COMP_NAME
    displayName: Component Name
    description: The name of the application component (e.g ui, backend, database).
    required: true
    value: api
  - name: ENV_NAME
    displayName: Environment name
    description: The name for this environment [dev, test, prod]
    required: true
    value: dev
  - name: ID
    displayName: Unique Identifier
    description: A unique identifier to allow for multiple instances (i.e. "-01").
    value: ""
  - name: PROJECT_NAMESPACE
    displayName: OpenShift Project Namespace
    description: The namespace of the OpenShift project containing the application.
    required: true
    value: jcxjin

  - name: KEYCLOAK_AUDIENCE
    displayName: Keycloak SSO audience
    description: The name of the client (i.e. pims-api).
    value: pims-api
  - name: KEYCLOAK_AUTHORITY
    displayName: Keycloak SSO Authority
    description: The full URL to the SSO Keycloak Admin client
      (i.e. https://dev.oidc.gov.bc.ca/auth/realms/xz0xtue5)
  - name: KEYCLOAK_ADMIN_AUTHORITY
    displayName: Keycloak SSO Admin Authority
    description: The full URL to the SSO Keycloak Admin client
      (i.e. https://dev.oidc.gov.bc.ca/auth/admin/realms/xz0xtue5)
