apiVersion: v1
kind: Template
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}${ID}-sso-client
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: Keycloak client JSON configuration
      labels:
        name: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}${ID}-sso-client
        app: ${APP_NAME}
        component: ${COMP_NAME}
        env: ${ENV_NAME}
        role: frontend
    typw: Opaque
    data:
      keycloak.json: '{
        "realm": "${KEYCLOAK_REALM}",
        "auth-server-url": "https://${ENV_NAME}.oidc.gov.bc.ca/auth",
        "ssl-required": "external",
        "resource": "${APP_NAME}-${COMP_NAME}",
        "public-client": true,
        "confidential-port": 0
        }'
parameters:
  - name: APP_NAME
    displayName: App Name
    description: The name of the application (grouped).
    required: true
    value: pims
  - name: COMP_NAME
    displayName: Component Name
    description: The name of the application component (e.g ui, backend, database).
    required: true
    value: app
  - name: ENV_NAME
    displayName: Environment name
    description: The name for this environment [dev, test, prod]
    required: true
    value: dev
  - name: ID
    displayName: Unique Identifier
    description: A unique identifier to allow for multiple instances (i.e. "-01").
    value: ""
  - name: PROJECT_NAMESPACE
    displayName: OpenShift Project Namespace
    description: The namespace of the OpenShift project containing the application.
    required: true
    value: jcxjin

  - name: KEYCLOAK_REALM
    displayName: Keycloak SSO realm
    description: Keycloak SSO realm, used by the frontend login.
    required: true
    value: xz0xtue5
