kind: Template
apiVersion: v1
name: pims-network-security-policy
parameters:
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "354028"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
  - name: NAME
    displayName: "The Application Name"
    description: "The name of the application."
    required: true
    value: "pims"
  - name: WEB_ROLE
    displayName: "The Web Application Role"
    description: "The web role/pod that will receive a request from the internet."
    required: true
    value: "web"
  - name: API_ROLE
    displayName: "The API Application Role"
    description: "The API role/pod that will receive a request from the internet."
    required: true
    value: "api"
  - name: DB_ROLE
    displayName: "The Database Application Role"
    description: "The DB role/pod that will receive a request from the internet."
    required: true
    value: "database"
  - name: BACKUP_ROLE
    displayName: "The Database Backup Application Role"
    description: "The backup role/pod that will receive a request from the internet."
    required: true
    value: "backup"
objects:
  # Allow the project namespace to communicate with k8s cluster api.
  - kind: NetworkSecurityPolicy
    apiVersion: security.devops.gov.bc.ca/v1alpha1
    metadata:
      name: project-to-k8s-api-${ENV_NAME}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
    spec:
      description: Allow pods to talk to the internal K8S api
      source:
        - - $namespace=${PROJECT_NAMESPACE}-${ENV_NAME}
      destination:
        - - int:network=internal-cluster-api-endpoint

  # Allow a namespace to talk to itself.
  - kind: NetworkSecurityPolicy
    apiVersion: security.devops.gov.bc.ca/v1alpha1
    metadata:
      name: intra-namespace-comms
    spec:
      description: "allow ${PROJECT_NAMESPACE} namespace to talk to itself"
      source:
        - - $namespace=${PROJECT_NAMESPACE}
      destination:
        - - $namespace=${PROJECT_NAMESPACE}
