kind: Template
apiVersion: v1
name: pod-to-internet-config
parameters:
  - name: NAME
    displayName: "The Application Name"
    description: "The name of the application."
    required: true
    value: "pims"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "dev"
  - name: ROLE
    displayName: "The Role"
    description: "The role/pod that will send requests to the internet."
    required: true
    value: "web"
objects:
  - kind: NetworkSecurityPolicy
    apiVersion: security.devops.gov.bc.ca/v1alpha1
    metadata:
      name: internal-ingress-${NAME}-${ROLE}
    spec:
      description: Allow a pod to open connections to the Internet.
      source:
        - - app=${NAME}
          - role=${ROLE}
          - env=${ENV_NAME}
      destination:
        - - ext:network=any
