kind: Template
apiVersion: v1
name: service-account-to-k8s-api-config
parameters:
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project that will allow the service account to communicate with the internet."
    required: true
    value: "354028"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for the environment [dev, test, prod, tools]"
    required: true
    value: "tools"
objects:
  - kind: NetworkSecurityPolicy
    apiVersion: security.devops.gov.bc.ca/v1alpha1
    metadata:
      name: service-account-to-k8s-api-${ENV_NAME}
    spec:
      description: Allow service accounts to run builds/deployments.
      source:
        - - $namespace=${PROJECT_NAMESPACE}-${ENV_NAME}
          - "@app:k8s:serviceaccountname=builder"
        - - $namespace=${PROJECT_NAMESPACE}-${ENV_NAME}
          - "@app:k8s:serviceaccountname=deployer"
      destination:
        - - int:network=internal-cluster-api-endpoint
