kind: Template
apiVersion: v1
metadata:
  name: docker-respository-config
parameters:
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "354028"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "tools"

  - name: DOCKER_SERVER
    displayName: "Docker Server Domain"
    description: "The name of the application (grouped)."
    required: true
    value: "docker-remote.artifacts.developer.gov.bc.ca"
  - name: DOCKER_USERNAME
    displayName: "Docker Username"
    description: "The username to connect to the Docker repository"
    required: true
  - name: DOCKER_PASSWORD
    displayName: "Docker User Password"
    description: "The password to connect to the Docker repository."
    required: true
  - name: DOCKER_EMAIL
    displayName: "Docker Email"
    description: "The email address for your docker account (not required)"
    value: ""
objects:
  # Add a resource secret to connect to remote Docker repository.
  - kind: Secret
    apiVersion: v1
    metadata:
      name: docker-authentication-${ENV_NAME}-secret
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: "Docker repository configuration"
      labels:
        name: docker-authentication-${ENV_NAME}-secret
        env: ${ENV_NAME}
    type: Opaque
    stringData:
      docker-server: ${DOCKER_SERVER}
      docker-username: ${DOCKER_USERNAME}
      docker-password: ${DOCKER_PASSWORD}
      docker-email: ${DOCKER_EMAIL}
