export enum ProjectTask {
  SURPLUS_DECLARATION_READINESS = 1,
  TRIPLE_BOTTOM_LINE = 2,
  REVIEW_COMPLETED_ERP = 3,
  REVIEW_COMPLETED_ERP_EXEMPT = 4,
  DOCUMENTS_RECEIVED_REVIEW_COMPLETED = 5,
  APPRAISAL_ORDERED = 6,
  APPRAISAL_RECEIVED = 7,
  // THERE IS NO 8
  PREPARATION_DUE_DILIGENCE = 9,
  FN_CONSULTATION_UNDERWAY = 10,
  FN_CONSULTATION_COMPLETE = 11,
  NOTIFICATION_EXEMPTION_TO_ADM = 12,
  CONFIRMATION_RECEIVED_FROM_ADM = 13,
  APPRAISAL_ORDERED_DUPLICATE = 14, // DUPLICATE - DO NOT USE
  APPRAISAL_RECEIVED_DUPLICATE = 15, // DUPLICATE - DO NOT USE
}
