apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: backup-database
  annotations:
    description: >-
      Make a remote SSH connection to the database backup service and start a backup.
    tags: oc,rsh,database,backup
spec:
  params:
    - name: PROJECT_NAMESPACE
      description: The project namespace name.
      type: string
      default: 354028-dev
    - name: DEPLOYMENT_CONFIG
      description: The name of the database backup DeploymentConfig.
      type: string
      default: pims-backup
    - name: ARGS
      description: >-
        The arguments to include when executing the backup.sh script.
        -l : List existing backups
        -h : Display help information
        -c : Display current configuration
        -1 : Run a single backup
        -r <spec> : Restore the database with the specified <spec>
      type: string
      default: '-1'

  tasks:
    - name: backup
      taskRef:
        name: oc-backup
        kind: Task
      params:
        - name: PROJECT_NAMESPACE
          value: $(params.PROJECT_NAMESPACE)
        - name: DEPLOYMENT_CONFIG
          value: $(params.DEPLOYMENT_CONFIG)
        - name: ARGS
          value: $(params.ARGS)
