apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: db-migration
  annotations:
    description: >-
      Run the database migration
    tags: oc,database,migration
spec:
  params:
    - name: IMAGE_TAG
      description: The tag that identifies the migration image to run.
      type: string
      default: latest
    - name: DEPLOY_TO
      description: Which environment to deploy to
      type: string
      default: dev

  tasks:
    - name: run
      taskRef:
        name: db-migration
        kind: Task
      params:
        - name: MIGRATION_IMAGE
          value: pims-migrations
        - name: DB_APP_NAME
          value: pims-database
        - name: PROJECT_SHORTNAME
          value: '354028'
        - name: IMAGE_TAG
          value: $(params.IMAGE_TAG)
        - name: DEPLOY_TO
          value: $(params.DEPLOY_TO)
