apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: redirect-route
  annotations:
    description: >-
      Update route and point to specified service.
    tags: oc,route
spec:
  params:
    - name: PROJECT_NAMESPACE
      description: The project namespace name.
      type: string
      default: 354028-dev
    - name: ROUTE
      description: The route name to update.
      type: string
      default: pims-app
    - name: SERVICE
      description: The service to redirect traffic to.
      type: string

  tasks:
    - name: redirect-route
      taskRef:
        name: oc-update-route
        kind: Task
      params:
        - name: PROJECT_NAMESPACE
          value: $(params.PROJECT_NAMESPACE)
        - name: ROUTE
          value: $(params.ROUTE)
        - name: SERVICE
          value: $(params.SERVICE)
