kind: Template
apiVersion: v1
metadata:
  name: pims-app-build
  annotations:
    openshift.io/display-name: Nginx with Node build
    description: Build template for a Nginx with Node build
    tags: pims-app
labels:
  app: pims
  component: app
  role: frontend
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${COMP_NAME}-base
      annotations:
        description: Keeps track of changes to the intermediate frontend artifacts image
    labels:
      name: ${APP_NAME}-${COMP_NAME}-base
      app: ${APP_NAME}
      component: ${COMP_NAME}
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${COMP_NAME}-base-${GIT_REF}
      annotations:
        description: Intermediate build that generates the frontend artifacts (html, javascript, images, etc)
    labels:
      name: ${APP_NAME}-${COMP_NAME}-base-${GIT_REF}
      app: ${APP_NAME}
      component: ${COMP_NAME}
    spec:
      runPolicy: Parallel
      completionDeadlineSeconds: 1800
      triggers:
        - type: ImageChange
        - type: ConfigChange
      source:
        type: Git
        git:
          uri: "${GIT_URL}"
          ref: "${GIT_REF}"
        contextDir: "${SOURCE_CONTEXT_DIR}"
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            namespace: ${BUILDIMAGE_NAMESPACE}
            name: ${BUILDIMAGE_NAME}:${BUILDIMAGE_TAG}
          incremental: false
      output:
        to:
          kind: ImageStreamTag
          name: ${APP_NAME}-${COMP_NAME}-base:${OUTPUT_IMAGE_TAG}
      resources:
        requests:
          cpu: 20m
          memory: 20Mi
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${COMP_NAME}
      annotations:
        description: Keeps track of changes to the final frontend image (embedded in nginx)
    labels:
      name: ${APP_NAME}-${COMP_NAME}
      app: ${APP_NAME}
      component: ${COMP_NAME}
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${COMP_NAME}-${GIT_REF}
      annotations:
        description: This (final) build takes the generated frontend artifacts and serves them through a static web server (nginx)
    labels:
      name: ${APP_NAME}-${COMP_NAME}-${GIT_REF}
      app: ${APP_NAME}
      component: ${COMP_NAME}
    spec:
      runPolicy: Parallel
      completionDeadlineSeconds: 1800
      triggers:
        - type: ImageChange
        - type: ConfigChange
      source:
        dockerfile: |-
          FROM ${APP_NAME}-${COMP_NAME}-base:${OUTPUT_IMAGE_TAG}
          COPY * /tmp/app/dist/
          CMD  /usr/libexec/s2i/run
        images:
          - from:
              kind: ImageStreamTag
              name: ${APP_NAME}-${COMP_NAME}-base:${OUTPUT_IMAGE_TAG}
            paths:
              - destinationDir: tmp
                sourcePath: "/opt/app-root/src/build/."
        type: Dockerfile
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            namespace: ${RUNTIMEIMAGE_NAMESPACE}
            name: ${RUNTIMEIMAGE_NAME}:${RUNTIMEIMAGE_TAG}
        type: Docker
      output:
        to:
          kind: ImageStreamTag
          name: ${APP_NAME}-${COMP_NAME}:${OUTPUT_IMAGE_TAG}
      resources:
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
parameters:
  - name: APP_NAME
    displayName: App Name
    description: The name of the application (grouped).
    required: true
    value: "pims"
  - name: COMP_NAME
    displayName: Component Name
    description: The name of the application component.
    required: true
    value: "app"

  - name: BUILDIMAGE_NAMESPACE
    displayName: Source Image Namespace
    description: The s2i image namespace which is used to build the code.
    value: "jcxjin-tools"
  - name: BUILDIMAGE_NAME
    displayName: Source Image Name
    description: The image to use as the Builder Image.
    value: "nodejs-10-rhel7"
  - name: BUILDIMAGE_TAG
    displayName: Source Image Tag
    description: The s2i image tag which is used to build the code.
    value: "1-30"

  - name: RUNTIMEIMAGE_NAMESPACE
    displayName: Source Image Namespace
    description: The s2i image namespace which is used to build the code.
    value: "jcxjin-tools"
  - name: RUNTIMEIMAGE_NAME
    displayName: Source Image Name
    description: The image to use as the Builder Image.
    value: "nginx-runtime"
  - name: RUNTIMEIMAGE_TAG
    displayName: Source Image Tag
    description: The s2i image tag which is used to build the code.
    value: "latest"

  - name: GIT_URL
    displayName: GIT Source Repo URL
    description: A GIT URL to your source code.
    required: true
    value: https://github.com/bcgov/PIMS.git
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: dev
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: false
    value: frontend

  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: latest

  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    value: "1"
  - name: MEMORY_LIMIT
    displayName: Memory Limit
    description: Maximum amount of memory the container can use.
    value: "6Gi"
