kind: Template
apiVersion: v1
metadata:
  name: pims-app-unittest
  annotations:
    openshift.io/display-name: Node 'x' build image to run tests
    description: Build template for a Node 'x' image to run tests
    tags: pims-app
labels:
  app: pims
  component: app
  role: frontend
objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${COMP_NAME}-unittest
      annotations:
        description: Defines how to build the application
    labels:
      name: ${APP_NAME}-${COMP_NAME}-unittest
      app: ${APP_NAME}
      component: ${COMP_NAME}
    spec:
      runPolicy: Parallel
      completionDeadlineSeconds: 1800
      triggers:
        - type: ImageChange
        - type: ConfigChange
      source:
        type: Git
        git:
          uri: "${GIT_REPO_URL}"
          ref: "${GIT_REF}"
        contextDir: "${SOURCE_CONTEXT_DIR}"
      strategy:
        type: Source
        sourceStrategy:
          env:
            - name: NODE_ENV
              value: dev
          from:
            kind: ImageStreamTag
            namespace: ${BUILDIMAGE_NAMESPACE}
            name: ${BUILDIMAGE_NAME}:${BUILDIMAGE_TAG}
          incremental: false
      output:
      postCommit:
        script: npm test
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
parameters:
  - name: APP_NAME
    displayName: App Name
    description: The name of the application (grouped).
    required: true
    value: "pims"
  - name: COMP_NAME
    displayName: Component Name
    description: The name of the application component.
    required: true
    value: "app"
  - name: BUILDIMAGE_NAMESPACE
    displayName: Source Image Namespace
    description: The s2i image namespace which is used to build the code.
    value: "jcxjin-tools"
  - name: BUILDIMAGE_NAME
    displayName: Source Image Name
    description: The image to use as the Builder Image.
    value: "nodejs-10"
  - name: BUILDIMAGE_TAG
    displayName: Source Image Tag
    description: The s2i image tag which is used to build the code.
    value: "latest"
  - name: GIT_REPO_URL
    displayName: GIT Source Repo URL
    description: A GIT URL to your source code.
    required: true
    value: https://github.com/bcgov/PIMS.git
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: dev
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: false
    value: frontend
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    value: "1"
  - name: MEMORY_LIMIT
    displayName: Memory Limit
    description: Maximum amount of memory the container can use.
    value: "6Gi"
