# This is a build template for .NET Core 3.1
# It will build a new image from the specified source control repo
# that will run your application.
kind: Template
apiVersion: v1
metadata:
  name: pims-db-build
  annotations:
    openshift.io/display-name: Microsoft SQL Server
    description: Relational database management system developed by Microsoft.
    tags: pims-db
objects:
  # The final build image.
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${COMP_NAME}
      annotations:
        description: Keeps track of changes in the database image
      labels:
        app: ${APP_NAME}
        component: ${COMP_NAME}
        role: database
  # The build config that will be created will be named for the branch you created it for.
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${COMP_NAME}-${GIT_REF}
      annotations:
        description: Defines how to build the database image
      labels:
        name: ${APP_NAME}-${COMP_NAME}-${GIT_REF}
        app: ${APP_NAME}
        component: ${COMP_NAME}
        role: database
        branch: ${GIT_REF}
    spec:
      completionDeadlineSeconds: 1800
      triggers:
        - type: ImageChange
        - type: ConfigChange
      runPolicy: Serial
      source:
        git:
          uri: ${GIT_URL}
          ref: ${GIT_REF}
        contextDir: ${CONTEXT_DIR}
        dockerfile: |-
          FROM ${MSSQL_IMAGE}:${MSSQL_IMAGE_TAG}
          RUN mkdir -p /usr/config
          WORKDIR /usr/config
          COPY . /usr/config
          USER root
          RUN chmod -R g=u /etc/passwd
          USER 10001
          ENTRYPOINT ["./entrypoint.sh"]
          EXPOSE 1433
          VOLUME ["/var/opt/mssql"]
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            namespace: "${PROJECT_NAMESPACE}-tools"
            name: ${MSSQL_IMAGE}:${MSSQL_IMAGE_TAG}
        type: Docker
      output:
        to:
          kind: ImageStreamTag
          name: ${APP_NAME}-${COMP_NAME}:${OUTPUT_IMAGE_TAG}
      resources:
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
parameters:
  - name: APP_NAME
    displayName: App Name
    description: The name of the application (grouped).
    required: true
    value: pims
  - name: COMP_NAME
    displayName: Component Name
    description: The name of the application component (e.g api, app, db).
    required: true
    value: db
  - name: PROJECT_NAMESPACE
    displayName: OpenShift Project Namespace
    description: The namespace of the OpenShift project containing the application.
    required: true
    value: jcxjin

  - name: GIT_URL
    displayName: Git Repository URL
    description: The URL of the repository with your application source code.
    required: true
    value: https://github.com/bcgov/PIMS.git
  - name: GIT_REF
    displayName: Git Reference
    description:
      Set this to a branch name, tag or other ref of your repository if you
      are not using the default branch.
    value: dev
  - name: CONTEXT_DIR
    displayName: Context Directory
    description: Set this to use a subdirectory of the source code repository
    value: database/mssql

  - name: MSSQL_IMAGE
    displayName: Microsoft SQL Server Image
    description: The s2i image which is used to host the database.
    required: true
    value: mssql-rhel-server
  - name: MSSQL_IMAGE_TAG
    displayName: Microsoft SQL Server Image tag
    description: The s2i image which is used to host the database.
    required: true
    value: 2019-latest

  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: latest

  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: "2"
  - name: MEMORY_LIMIT
    displayName: Memory Limit
    description: Maximum amount of memory the container can use.
    required: true
    value: 6Gi
