kind: Template
apiVersion: v1
metadata:
  name: s2i-caddy
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all objects.
    required: true
    value: s2i-caddy
  - name: ROLE_NAME
    displayName: Role Name
    description: The name of the application component role (e.g ui, web, api, database).
    required: true
    value: web-server
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "354028"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "tools"

  - name: GIT_REPO
    displayName: Git Repo URL
    description: >-
      The URL to your GIT repo, don't use the this default unless your just
      experimenting.
    required: true
    value: "https://github.com/BCDevOps/s2i-caddy.git"
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: master
  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: latest

  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: "1"
  - name: MEMORY_LIMIT
    displayName: Memory Limit
    description: Maximum amount of memory the container can use.
    required: true
    value: 6Gi
objects:
  # Where to keep the base source image.
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: alpine-caddy
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      labels:
        name: ${NAME}
        app: ${NAME}
        role: ${ROLE_NAME}
        env: ${ENV_NAME}
    spec:
      tags:
        - name: v2
          from:
            kind: DockerImage
            name: "caddy:2.0.0-rc.3-alpine"
          generation: null
          importPolicy: {}
    status:
      dockerImageRepository: ""

  # Where to keep the built image.
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${NAME}"
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      labels:
        name: ${NAME}
        app: ${NAME}
        role: ${ROLE_NAME}
        env: ${ENV_NAME}
    spec: {}
    status:
      dockerImageRepository: ""

  # How to build the image.
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${NAME}"
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      labels:
        name: ${NAME}
        app: ${NAME}
        role: ${ROLE_NAME}
        env: ${ENV_NAME}
    spec:
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChange: {}
      source:
        type: Git
        git:
          uri: "${GIT_REPO}"
          ref: "${GIT_REF}"
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: "alpine-caddy:v2"
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}:${OUTPUT_IMAGE_TAG}"
      resources:
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
      postCommit: {}
      completionDeadlineSeconds: 1200
      failedBuildsHistoryLimit: 2
      successfulBuildsHistoryLimit: 5
    status:
      lastVersion: 0
