apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/displayName: openshift client
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: cli
  name: oc-deploy-with-tag
  labels:
    app.kubernetes.io/version: "0.1"
    operator.tekton.dev/provider-type: redhat
spec:
  description: >-
    This task will tag a specific image with the environment name.
    This will deploy the image if there is a DeployConfig trigger listening for the environment tag.
  params:
    - name: PROJECT
      description: The project namespace.
      type: string
      default: '354028'
    - name: IMAGE_NAME
      description: The name given to the built image.
      type: string
    - name: IMAGE_TAG
      description: The tag given to the built image.
      type: string
      default: "latest"
    - name: ENV
      description: The environment to deploy to.
      type: string
    - name: TIMEOUT
      description: The timeout before it will stop waiting for the pod to become available.
      type: string
      default: "60s"

  steps:
    - name: deploy
      image: "image-registry.openshift-image-registry.svc:5000/openshift/cli:latest"
      resources: {}
      script: |
        echo "Tagging image to trigger deployment to $(params.ENV)"
        oc tag $(params.IMAGE_NAME):$(params.IMAGE_TAG) $(params.IMAGE_NAME):$(params.ENV)

        echo "Waiting for deployment to roll out"
        oc wait --for=condition=available --timeout=$(params.TIMEOUT) dc/$(params.IMAGE_NAME) -n $(params.PROJECT)-$(params.ENV)

        # timeout(10) {
        # dc.rollout().status('--watch=true')
        # }
