apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: owasp-scanner
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Security
    tekton.dev/tags: security
    tekton.dev/displayName: owasp zap scanner
    tekton.dev/platforms: linux/amd64
spec:
  description: >-
    The worlds most widely used web app scanner. Free and open source.
    Actively maintained by a dedicated international team of volunteers.
  workspaces:
    - name: owasp-settings
      optional: true
      mountPath: /zap/wrk
  params:
    - name: TARGET_URL
      description: Host URL where the sonarqube server is running
      default: "https://example.com"
    - name: SCAN_TYPE
      description: Options include quick or full.
      default: "quick"
    - name: SCAN_DURATION
      description: The duration of the OWASP scan.
      default: "1"
  steps:
    - name: owasp-scan
      image: owasp/zap2docker-stable
      workingDir: $(workspaces.owasp-settings.path)
      script: |
        #!/bin/bash
        if [ $(params.SCAN_TYPE) = "quick" ]
        then
          echo "performing quick scan"
          zap-baseline.py -t $(params.TARGET_URL) -d -g gen.conf -J owasp-quick-results.json -m $(params.SCAN_DURATION) -I
          cat $(workspaces.owasp-settings.path)/owasp-quick-results.json
        elif [ $(params.SCAN_TYPE) = "full" ]
        then
          echo "performing full scan"
          zap-full-scan.py -t $(params.TARGET_URL) -d -g gen.conf -J owasp-full-results.json -m $(params.SCAN_DURATION) -I
          cat $(workspaces.owasp-settings.path)/owasp-full-results.json
        else
          echo "ERROR: Scan type must be set to quick or full."
          exit 1
        fi
