kind: Template
apiVersion: v1
metadata:
  name: migration-job
parameters:
  - name: IMAGE
    displayName: Image Name
    description: Docker registry reference image.
    required: true
    value: pims-migrations
  - name: IMAGE_TAG
    displayName: Image Tag Name
    description: The image tag that will be used for this job.
    required: true
    value: dev
  - name: NAMESPACE
    description: Target namespace reference (i.e. 'jcxjin-tools')
    displayName: Namespace
    required: true
    value: jcxjin-tools
  - name: ENV_NAME
    displayName: Environment name
    description: The name for this environment [dev, test, prod]
    required: true
    value: dev
  - name: ASPNETCORE_ENVIRONMENT
    displayName: AspNetCore Environment
    description: The ASP Net Core deployment environment setting,
      [Development, Staging, Production].
    required: true
    value: Production
objects:
  - kind: Pod
    apiVersion: v1
    metadata:
      generateName: migration-job-
    spec:
      restartPolicy: Never
      activeDeadlineSeconds: 900
      containers:
        - name: dotnet-ef
          image: docker-registry.default.svc:5000/${NAMESPACE}/${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: ${ASPNETCORE_ENVIRONMENT}
            - name: ConnectionStrings__PIMS
              valueFrom:
                configMapKeyRef:
                  name: pims-api-${ENV_NAME}-db-client
                  key: CONNECTION_STRINGS_PIMS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pims-db-${ENV_NAME}-secret
                  key: DB_PASSWORD
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500Mi
