# This is a build template for .NET Core 3.1
# It will build a new image from the specified source control repo
# that will run your application.
kind: Template
apiVersion: v1
metadata:
  name: pims-api-build
  annotations:
    openshift.io/display-name: .NET Core 3.1 Build Template
    description: Build template for a .NET Core 3.1 application.
    tags: pims-api
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${COMP_NAME}
      annotations:
        description: Keeps track of changes in the application image
      labels:
        app: ${APP_NAME}
        component: ${COMP_NAME}
        role: backend
  # The build config that will be created will be named for the branch you created it for.
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${COMP_NAME}-${GIT_REF}
      annotations:
        description: Defines how to build the application
      labels:
        name: ${APP_NAME}-${COMP_NAME}-${GIT_REF}
        app: ${APP_NAME}
        component: ${COMP_NAME}
        role: backend
        branch: ${GIT_REF}
    spec:
      triggers:
        - type: ImageChange
        - type: ConfigChange
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: ${GIT_URL}
          ref: ${GIT_REF}
        contextDir: ${SOURCE_CONTEXT_DIR}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: ${DOTNET_BUILDER_IMAGE}:${DOTNET_BUILDER_TAG}
          # scripts: https://raw.githubusercontent.com/bcgov/PIMS/dev/.s2i/bin
          env:
            - name: DOTNET_CONFIGURATION
              value: ${DOTNET_CONFIGURATION}
            - name: DOTNET_STARTUP_PROJECT
              value: ${DOTNET_STARTUP_PROJECT}
            - name: DOTNET_PUBLISH_READYTORUN
              value: ${DOTNET_PUBLISH_READYTORUN}
            - name: DOTNET_TEST_PROJECTS
              value: ${DOTNET_TEST_PROJECTS}
            - name: DOTNET_TOOLS
              value: ${DOTNET_TOOLS}
      output:
        to:
          kind: ImageStreamTag
          name: ${APP_NAME}-${COMP_NAME}:${OUTPUT_IMAGE_TAG}
      resources:
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
parameters:
  - name: APP_NAME
    displayName: App Name
    description: The name of the application (grouped).
    required: true
    value: pims
  - name: COMP_NAME
    displayName: Component Name
    description: The name of the application component (e.g ui, backend, database).
    required: true
    value: api

  - name: GIT_URL
    displayName: Git Repository URL
    description: The URL of the repository with your application source code.
    required: true
    value: https://github.com/bcgov/PIMS.git
  - name: GIT_REF
    displayName: Git Reference
    description:
      Set this to a branch name, tag or other ref of your repository if you
      are not using the default branch.
    value: dev
  - name: SOURCE_CONTEXT_DIR
    displayName: Context Directory
    description: Set this to use a subdirectory of the source code repository
    value: backend

  - name: DOTNET_BUILDER_IMAGE
    displayName: .NET builder
    description: The s2i image which is used to build the code.
    required: true
    value: dotnet-31-rhel7
  - name: DOTNET_BUILDER_TAG
    displayName: .NET builder tag
    description: The s2i image tag which is used to build the code.
    required: true
    value: "3.1"

  - name: DOTNET_STARTUP_PROJECT
    displayName: Startup Project
    description:
      Set this to a project file (e.g. csproj) or a folder containing a single
      project file.
    required: true
    value: api/Pims.Api.csproj
  - name: DOTNET_PUBLISH_READYTORUN
    displayName: Ahead-of-time compilation
    description: Set this to 'true' to perform an ahead-of-time compilation.
    value: "true"
  - name: DOTNET_CONFIGURATION
    displayName: Configuration
    description: Set this to configuration (Release/Debug).
    value: "Release"
  - name: DOTNET_TEST_PROJECTS
    displayName: Test projects
    description: Set this to a space separated list of test projects to run before publishing.

  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: latest
  - name: DOTNET_TOOLS
    displayName: Output Tools
    description: Dotnet tools to install during build.
    required: true
    value: dotnet-ef

  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: "1"
  - name: MEMORY_LIMIT
    displayName: Memory Limit
    description: Maximum amount of memory the container can use.
    required: true
    value: 6Gi
