---
kind: Template
apiVersion: v1
metadata:
  name: "${APP_NAME}"
parameters:
  - name: NAME
    displayName: Name
    description: The suffix for all created objects
    required: false
    value: proxy-caddy
  - name: BUILD_PROJECT
    displayName: Build project
    description: The suffix for all created objects
    required: false
    value: jcxjin-dev
objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "${NAME}"
      creationTimestamp:
      labels:
        app: "${NAME}"
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
        resources: {}
        activeDeadlineSeconds: 21600
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - "${NAME}"
            from:
              kind: ImageStreamTag
              namespace: "${BUILD_PROJECT}"
              name: "${NAME}:latest"
      replicas: 1
      revisionHistoryLimit: 10
      test: false
      selector:
        app: "${NAME}"
        deploymentconfig: "${NAME}"
      template:
        metadata:
          creationTimestamp:
          labels:
            app: "${NAME}"
            deploymentconfig: "${NAME}"
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
        spec:
          containers:
            - name: "${NAME}"
              image: " "
              ports:
                - containerPort: 2015
                  protocol: TCP
              resources: {}
              terminationMessagePath: "/dev/termination-log"
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${NAME}"
      creationTimestamp:
      labels:
        app: "${NAME}"
    spec:
      ports:
        - name: 2015-tcp
          protocol: TCP
          port: 2015
          targetPort: 2015
      selector:
        app: "${NAME}"
        deploymentconfig: "${NAME}"
      type: ClusterIP
      sessionAffinity: None
