apiVersion: v1
kind: Template
metadata:
  name: pims-app-deploy
  annotations:
    openshift.io/display-name: Nginx with Node build
    description: Deployment template for a Nginx with Node build
    tags: pims-app,react,nginx
labels:
  app: pims
  component: app
  role: frontend
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APP_NAME}-${COMP_NAME}
    namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
    annotations:
      description: "Defines how to deploy ${APP_NAME}-${COMP_NAME}"
  labels:
    name: ${APP_NAME}-${COMP_NAME}
    app: ${APP_NAME}
    component: ${COMP_NAME}
    role: infrastructure
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      component: ${COMP_NAME}
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        name: ${APP_NAME}-${COMP_NAME}
        labels:
          app: ${APP_NAME}
          component: ${COMP_NAME}
      spec:
        volumes:
        - name: "${APP_NAME}-${COMP_NAME}-keycloak-config-volume"
          configMap:
            name: "${KEYCLOAK_CONFIG_MAP_NAME}"
            items:
            - key: "${KEYCLOAK_CONFIG_FILE_NAME}"
              path: "${KEYCLOAK_CONFIG_FILE_NAME}"
        containers:
        - image: ${APP_NAME}-${COMP_NAME}
          imagePullPolicy: Always
          name: ${APP_NAME}-${COMP_NAME}
          ports:
          - containerPort: ${{APP_PORT}}
            protocol: TCP
          env:
          - name: API_URL
            value: "${API_URL}"
          - name: API_SERVICE_NAME
            value: "${API_SERVICE_NAME}"
          - name: API_PATH
            value: "${API_PATH}"
          - name: RealIpFrom
            value: "${REAL_IP_FROM}"
          resources:
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
          volumeMounts:
          - name: "${APP_NAME}-${COMP_NAME}-keycloak-config-volume"
            mountPath: "${KEYCLOAK_CONFIG_MOUNT_PATH}${KEYCLOAK_CONFIG_FILE_NAME}"
            subPath: "${KEYCLOAK_CONFIG_FILE_NAME}"
          livenessProbe:
            httpGet:
              path: "/nginx_status"
              port: ${{APP_PORT}}
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 60
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: "/nginx_status"
              port: ${{APP_PORT}}
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 60
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${APP_NAME}-${COMP_NAME}"
        from:
          kind: ImageStreamTag
          namespace: "${SOURCEIMAGE_NAMESPACE}"
          name: "${APP_NAME}-${COMP_NAME}:${SOURCEIMAGE_TAG}"
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APP_NAME}-${COMP_NAME}
    namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
  labels:
    name: ${APP_NAME}-${COMP_NAME}
    app: ${APP_NAME}
    component: ${COMP_NAME}
    role: infrastructure
  spec:
    ports:
    - name: ${APP_PORT}-tcp
      port: ${{APP_PORT}}
      protocol: TCP
      targetPort: ${{APP_PORT}}
    selector:
      app: ${APP_NAME}
      component: ${COMP_NAME}
    sessionAffinity: None
    type: ClusterIP
- kind: Route
  apiVersion: v1
  metadata:
    name: ${APP_NAME}-${COMP_NAME}
    namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
  labels:
    name: ${APP_NAME}-${COMP_NAME}
    app: ${APP_NAME}
    component: ${COMP_NAME}
    role: infrastructure
    env: ${ENV_NAME}
  spec:
    host: "${APP_DOMAIN}"
    port:
      targetPort: ${APP_PORT}-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${APP_NAME}-${COMP_NAME}
      weight: 100
parameters:
- name: APP_NAME
  displayName: App Name
  description: The name of the application (grouped).
  required: true
  value: "pims"
- name: COMP_NAME
  displayName: Component Name
  description: The name of the application component.
  required: true
  value: "app"
- name: ENV_NAME
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod
  required: true
  value: "dev"
- name: SOURCEIMAGE_NAMESPACE
  displayName: Image Namespace
  description:
    The namespace of the OpenShift project containing the imagestream for the
    application.
  required: true
  value: "jcxjin-tools"
- name: SOURCEIMAGE_TAG
  displayName: Source branch TAG name
  description: The TAG name for this branch [dev, test, prod]
  required: true
  value: "dev"
- name: PROJECT_NAMESPACE
  displayName: Image Namespace
  description:
    The namespace of the OpenShift project containing the application.
  required: true
  value: "jcxjin"
- name: APP_DOMAIN
  displayName: Application Hostname
  description:
    The exposed hostname that will route to the the .NET Core service, if left blank a
    value will be defaulted.
  value: "pims-dev.pathfinder.gov.bc.ca"
- name: APP_PORT
  displayName: Application Port
  description: The port used to communicate with the Pod
  value: "8080"

- name: KEYCLOAK_CONFIG_FILE_NAME
  displayName: keycloak.json Config File Name
  description: The name of the configuration file to be used for keycloak.json.
  required: true
  value: keycloak.json
- name: KEYCLOAK_CONFIG_MAP_NAME
  displayName: keycloak.json Config Map Name
  description: The name of the configuration map holding the data to configure the
    React app.
  required: true
  value: keycloak-frontend-secrets
- name: KEYCLOAK_CONFIG_MOUNT_PATH
  displayName: keycloak.json Mount Path
  description: The path to use to mount the config file.
  required: true
  value: "/tmp/app/dist/"

- name: REAL_IP_FROM
  description: OpenShift cluster private IP range in CIDR notation, used by Nginx
    ngx_http_realip_module.
  displayName: OpenShift Cluster IP Range
  required: true
  value: 172.51.0.0/16
- name: API_URL
  description: The default URL to use when proxying requests to the application's
    API.  The value here will be overridden if a API_SERVICE_NAME is defined.
  displayName: API URL
  required: false
  value: ''
- name: API_SERVICE_NAME
  description: The name of the service endpoint for the API.  Used to wire up to an
    API endpoint within the same project; overriding the URL defined by API_URL.
  displayName: API Service Name
  required: false
  value: api
- name: API_PATH
  description: The root path for the API.  Used in conjunction with API_SERVICE_NAME.
  displayName: API Path
  required: true
  value: "/api"

- name: CPU_LIMIT
  displayName: CPU Limit
  description: Maximum amount of CPU the container can use.
  value: "1"
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the container can use.
  value: 4Gi
- name: CPU_REQUEST
  displayName: CPU Request
  description: Starting amount of CPU the container can use.
  value: 100m
- name: MEMORY_REQUEST
  displayName: Memory Request
  description: Starting amount of memory the container can use.
  value: 2Gi
