apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: pipeline-service-account-role
  annotations:
    description: Service account role for pipelines
    openshift.io/display-name: Pipeline Service Account Role
    openshift.io/long-description: This template deploys a service-account role for pipelines
    tags: tekton,pipeline

parameters:
  - name: NAME
    displayName: Service Account Name
    description: The name of the service-account
    required: true
    value: pipeline

  - name: PROJECT_NAMESPACE
    displayName: OpenShift Project Namespace
    description: The namespace of the OpenShift project containing the application.
    required: true
    value: '354028'
  - name: ENV_NAME
    displayName: Environment name
    description: The name for this environment [dev, test, prod]
    required: true
    value: dev

objects:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: ${NAME}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      labels:
        name: ${NAME}
    rules:
      - apiGroups:
          - apps.openshift.io
        resources:
          - deploymentconfigs
        verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
          - delete
      - apiGroups:
          - apps
        resources:
          - deployments
        verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
          - delete
      - apiGroups:
          - batch
        resources:
          - jobs
        verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
          - delete
      - apiGroups:
          - ""
        resources:
          - services
          - configmaps
          - secrets
          - pods
          - pods/attach
          - pods/exec
        verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
          - delete
      - apiGroups:
          - ""
        resources:
          - endpoints
        verbs:
          - get
          - patch
          - update
          - create
          - list
          - watch
          - delete
      - apiGroups:
          - ""
        resources:
          - pods
        verbs:
          - get
          - list
          - patch
          - update
          - watch
      - apiGroups:
          - route.openshift.io
        resources:
          - routes
        verbs:
          - get
          - update
          - patch
          - watch

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: ${NAME}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      labels:
        name: ${NAME}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: ${NAME}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
    subjects:
      - kind: ServiceAccount
        name: ${NAME}
        namespace: ${PROJECT_NAMESPACE}-tools
