apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: pipeline-service-account
  annotations:
    description: Service account for pipelines
    openshift.io/display-name: Pipeline Service Account
    openshift.io/long-description: This template deploys a service-account for pipelines
    tags: tekton,pipeline

parameters:
  - name: NAME
    displayName: Service Account Name
    description: The name of the service-account
    required: true
    value: "pipeline"

objects:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
