### SCHEMAS ###
components:
  schemas:
    EvaluationCommon:
      type: object
      properties:
        EvaluationKeyId:
          type: integer
          example: 0
        Value:
          type: number
          example: 100
        Year:
          type: integer
          example: 2024
    EvaluationPost: 
      allOf:
        - $ref: '#/components/schemas/EvaluationCommon'
        - type: object 
          properties:
            isNew:
              type: boolean
              value: true
    Evaluation: 
      allOf:
        - $ref: '#/components/schemas/EvaluationCommon'
        - $ref: '#/components/schemas/CommonEntityProperties'
        - type: object 
          properties:
            Note:
              type: string
              example: 'Evaulation note'
            isNew: null # needed specifically so it doesn't show up
    BuildingEvaluation:
      allOf:
        - $ref: '#/components/schemas/Evaluation'
        - type: object 
          properties:
            BuildingId:
              type: integer
              example: 1
    ParcelEvaluation:
      allOf:
        - $ref: '#/components/schemas/Evaluation'
        - type: object 
          properties:
            ParcelId:
              type: integer
              example: 1
    FiscalCommon:
      type: object
      properties:
        EffectiveDate:
          type: string
          example: '2024-03-09T08:00:00.000Z'
        FiscalKeyId:
          type: integer
          example: 0
        FiscalYear:
          type: string
          example: 2024
          description: Is a string due to historical 24/23 storage.
        Value:
          type: number
          example: 100
        isNew:
          type: boolean
          example: true
    FiscalPost:
      allOf:
        - $ref: '#/components/schemas/FiscalCommon'
        - type: object 
          properties:
            isNew:
              type: boolean
              value: true
    Fiscal: 
      allOf:
        - $ref: '#/components/schemas/FiscalCommon'
        - $ref: '#/components/schemas/CommonEntityProperties'
        - type: object 
          properties:
            Note:
              type: string
              example: 'Fiscal note'
            isNew: null # needed specifically so it doesn't show up
    BuildingFiscal:
      allOf:
        - $ref: '#/components/schemas/Fiscal'
        - type: object 
          properties:
            BuildingId:
              type: integer
              example: 1
    ParcelFiscal:
      allOf:
        - $ref: '#/components/schemas/Fiscal'
        - type: object 
          properties:
            ParcelId:
              type: integer
              example: 1
