export enum MonetaryType {
  GAIN_BEFORE_SPL =1,
INTEREST_COMPONENT=2,
NET_PROCEEDS=3,
OCG_GAIN_LOSS=4,
OCG_FINANCIAL_STATEMENT=5,
OFFER_AMOUNT=6,
PROGRAM_COST=7,
REALTOR_COMMISION=8,
SALES_COST=9,
}
