/**
 * Timestamp enum, identifying all types of timestamps.
 */
export enum TimestampType {
  ADJUSTED_ON = 1,
  APPROVED_FOR_SPL_ON = 2,
  CLEARANCE_NOTIFICATION_SENT_ON = 3,
  DISPOSED_ON = 4,
  EXEMPTION_APPROVED_ON = 5,
  FINAL_FORM_SIGNED_ON = 6,
  INTEREST_RECEIVED_ON = 7,
  OFFER_ACCEPTED_ON = 8,
  REMOVAL_FROM_SPL_APPROVED_ON = 9,
  REMOVAL_FROM_SPL_REQUEST_ON = 10,
  REQUEST_FOR_SPL_RECEIVED_ON = 11,
  TRANSFERRED_WITHIN_GRE_ON = 12,
  MARKETED_ON = 13,
}
