apiVersion: v1
kind: Template
metadata:
  name: pims-kibana-deploy
  annotations:
    openshift.io/display-name: PIMS Kibana
    description: Deployment template for Kibana
    tags: pims-logging
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: pims-kibana-elasticsearch-password-secret
      namespace: ${PROJECT_NAME}
      annotations:
        description: "Elastic search secrets for Kibana"
      labels:
        name: pims-kibana-elasticsearch-password-secret
        app: ${APP_NAME}
        component: tools
    type: Opaque
    stringData:
      ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      namespace: ${PROJECT_NAME}
      name: ${APP_NAME}-config
      labels:
        app: ${APP_NAME}
    data:
      kibana.yml: |-
        server.host: "0"
        server.name: ${APP_NAME}

        elasticsearch.hosts: ["http://${ELASTICSEARCH_SVC_NAME}.${PROJECT_NAME}.svc.cluster.local:9200"]
        elasticsearch.username: elastic
        elasticsearch.password: ${ELASTICSEARCH_PASSWORD}
  - kind: Service
    apiVersion: v1
    metadata:
      namespace: ${PROJECT_NAME}
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      type: NodePort
      ports:
        - port: 5601
          name: webinterface
      selector:
        app: ${APP_NAME}

  - kind: Route
    apiVersion: v1
    metadata:
      labels:
        name: ${APP_NAME}
      name: ${APP_NAME}
      namespace: ${PROJECT_NAME}
    spec:
      host: ${KIBANA_DOMAIN}
      to:
        name: ${APP_NAME}
        kind: Service
        weight: 100
      tls:
        termination: edge
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      namespace: ${PROJECT_NAME}
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      replicas: 1
      selector:
        app: ${APP_NAME}
      template:
        metadata:
          labels:
            app: ${APP_NAME}
        spec:
          containers:
            - name: ${APP_NAME}
              image: docker.elastic.co/kibana/kibana:7.3.0
              env:
                - name: ELASTICSEARCH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: pims-kibana-elasticsearch-password-secret
                      key: ELASTICSEARCH_PASSWORD
              ports:
                - containerPort: 5601
                  name: webinterface
              volumeMounts:
                - name: config
                  mountPath: /usr/share/kibana/config/kibana.yml
                  readOnly: true
                  subPath: ${APP_NAME}.yml
          volumes:
            - name: config
              configMap:
                name: ${APP_NAME}-config
parameters:
  - name: ELASTIC_PASSWORD
    displayName: Elastic Password
    description: Elastic Password
    required: true
  - name: PROJECT_NAME
    displayName: Project Name
    description: Project Name
    required: true
    value: "jcxjin-tools"
  - name: ELASTICSEARCH_SVC_NAME
    displayName: Elasticsearch service Name
    description: Elasticsearch service Name
    required: true
    value: "elasticsearch"
  - name: APP_NAME
    displayName: Application Name
    description: Application Name
    required: true
    value: "kibana"
  - name: ROLE_NAME
    displayName: Role Name
    description: Role Name
    required: true
    value: "master"
  - name: KIBANA_DOMAIN
    displayName: Kibana domain
    description: Kibana domain
    required: true
    value: pims-kibana.pathfinder.gov.bc.ca
