name: APP (React 18) - Jest Test Coverage

on:
  pull_request:
    types: [opened, synchronize] # Triggered by opened or changed pull requests.
    branches: [dev]
    paths:
      - 'frontend/**' # Triggers on changes to files in the frontend/ directory.
      - '!frontend/cypress/**' # Will not trigger on changes to the following.
      - '!frontend/cypress.config.*'
      - '!frontend/.*'
      - '!frontend/Dockerfile*'
      - '!frontend/nginx.conf'
      - '!frontend/vite.config.*'
      - '!frontend/tsconfig.json'
      - '!frontend/README.md'

jobs:
  codeclimate-jest-coverage:
    runs-on: ubuntu-latest
    env:
      GIT_BRANCH: ${{ github.event.pull_request.head.ref }}
      GIT_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      CC_TEST_REPORTER_ID: 37fdb6f058122c17fc2419b78b02b1d5582694f7cd84a2b735de8eec235e9c5b

    steps:
      # Confirm GitHub ENVs.
      - name: Echo ENVs
        run: |
          echo $GIT_BRANCH
          echo $GIT_COMMIT_SHA

      # Checkout code from Repo.
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Import Code Climate test reporter.
      - name: Import Code Climate
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter

      # Allow test reporter to be executed.
      - name: Execute Permissions for Code Climate Binary
        run: |
          chmod +x ./cc-test-reporter

      # Notifies Code Climate of impending report.
      - name: Test Reporter Before Build
        run: |
          ./cc-test-reporter before-build

      # Install dependencies.
      - name: Install Dependencies
        working-directory: ./frontend
        run: |
          npm i

      # Generate coverage report.
      - name: Run Coverage Report
        working-directory: ./frontend
        run: |
          npm run coverage

      # Use lcov to format coverage for Code Climate
      # -t is for coverage type
      - name: Format Test Coverage
        run: |
          ./cc-test-reporter format-coverage ${{ github.workspace }}/frontend/coverage/lcov.info -t lcov --output ${{ github.workspace }}/frontend/coverage/coverage.json

      # Upload coverage to Code Climate.
      # -i is for input, -d for detached
      - name: Upload Coverage
        run: |
          ./cc-test-reporter upload-coverage -d -i ${{ github.workspace }}/frontend/coverage/coverage.json
