name: App Cypress Tests - Dev

on:
  schedule:
    - cron: '0 20 * * *' # Every day at 8:00pm UTC - roughly noon Pacific Time.
  workflow_dispatch:

jobs:
  e2e-tests-dev:
    runs-on: ubuntu-22.04
    # Cypress Docker Image
    # - with Chrome, Firefox, and Edge v113 pre-installed.
    # - Node v18.16.0
    container: cypress/browsers:node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1

    steps:
      # Checkout PIMS Github Repository.
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Run Cypress E2E Tests.
      - name: Cypress Run E2E Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          working-directory: frontend
          command: npm run cypress:e2e
          config-file: cypress.config.ts
          config: baseUrl=https://pims-dev.apps.silver.devops.gov.bc.ca
        env:
          auth_client_id: pims-frontend-4391
          keycloak_user: ${{ secrets.TEST_IDIR_USERNAME }}
          keycloak_password: ${{ secrets.TEST_IDIR_PASSWORD }}
