name: APP Linting Check

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/app-lint.yaml"
  workflow_dispatch:

jobs:
  lint-app:
    name: Lint Frontend App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Could optimize this by only installing necessary dependencies
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm i --only=dev

      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint

      - name: Run Prettier
        working-directory: ./frontend
        run: npm run check 
