name: App Cypress Tests - Dev

on:
  schedule:
    - cron: '0 21 * * 1-5' # Every weekday at 9:00pm UTC - roughly 1:00pm Pacific Time.
  workflow_dispatch:

jobs:
  e2e-tests-dev:
    runs-on: ubuntu-22.04
    # Cypress Docker Image
    # - with Chrome, Firefox, and Edge v113 pre-installed.
    # - Node v18.16.0
    container: cypress/browsers:node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1

    steps:
      # Checkout PIMS Github Repository.
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      # Install NPM Dependencies.
      - name: Install Dependencies
        run: |
          cd ./frontend
          npm i

      # Run Cypress E2E Tests.
      - name: Cypress Run E2E Tests
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_KEYCLOAK_USER: ${{ secrets.TEST_IDIR_USERNAME }}
          CYPRESS_KEYCLOAK_PASSWORD: ${{ secrets.TEST_IDIR_PASSWORD }}
        with:
          browser: chrome
          working-directory: frontend
          command: npm run cypress:e2e-dev
          config-file: cypress.config.ts
