name: Create JIRA Dependency Tickets
# This workflow creates JIRA tickets for any issues found during the validate workflow.

on:
    workflow_run:
        workflows: ['NPM Dependency Reports']
        types: [completed]
        branches:
            - 'main'
    pull_request:
        branches:
            - 'main'
        types: [synchronize]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        # if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps: 
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Get API NPM Dependency Issues
              id: get_api_issue
              run: |
                # Get issue content
                API_CONTENT=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  "https://api.github.com/repos/${{ github.repository }}/issues?state=open" | \
                  jq -r '.[] | select(.title == "express-api NPM Dependency Report") | .body')
                
                # Store the content directly to a file for later use
                echo "$API_CONTENT" > api_content.txt
                
                echo "Found issue content for express-api NPM Dependency Report"
            
            - name: Get APP NPM Dependency Issues
              id: get_app_issue
              run: |
                # Get issue content
                APP_CONTENT=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  "https://api.github.com/repos/${{ github.repository }}/issues?state=open" | \
                  jq -r '.[] | select(.title == "react-app NPM Dependency Report") | .body')
                
                # Store the content directly to a file for later use
                echo "$APP_CONTENT" > app_content.txt
                
                echo "Found issue content for react-app NPM Dependency Report"
          
            # Send issue content to JIRA webhook using curl
            - name: Create JIRA Tickets
              run: |
                # Create JIRA ticket for API issues
                if [ -s api_content.txt ]; then
                  echo "Sending API dependency report to Jira..."

                  # Debug: check the content
                  echo "File size: $(wc -c api_content.txt)"
                  echo "First few characters:"
                  head -c 100 api_content.txt

                  # Prepare the payload by wrapping the content in the expected structure
                  jq -n --arg title "express-api NPM Dependency Report" \
                        --arg body "$(cat api_content.txt)" \
                        '{
                          "data": {
                            "title": $title,
                            "body": $body
                          }
                        }' > api_payload.json
                  
                  # Debug the final payload
                  echo "\nFinal payload structure:"
                  cat api_payload.json | jq '.'
                  
                  API_RESPONSE=$(curl -X POST \
                    -H "Content-Type: application/json" \
                    -H "X-Automation-Webhook-Token: ${{ secrets.JIRA_API_TOKEN }}" \
                    --data @api_payload.json \
                    -w "\n%{http_code}" \
                    -s \
                    "${{ secrets.JIRA_WEBHOOK_URL }}")
                  
                  API_HTTP_CODE=$(echo "$API_RESPONSE" | tail -n1)
                  API_CONTENT_RESPONSE=$(echo "$API_RESPONSE" | sed '$d')
                  
                  echo "\nAPI Request Status Code: $API_HTTP_CODE"
                  
                  if [ "$API_HTTP_CODE" -ge 200 ] && [ "$API_HTTP_CODE" -lt 300 ]; then
                    echo "✅ API Jira ticket created successfully"
                  else
                    echo "❌ Failed to create API Jira ticket. Status code: $API_HTTP_CODE"
                    echo "Response: $API_CONTENT_RESPONSE"
                    exit 1
                  fi
                else
                  echo "No API content found to send to Jira"
                fi
                
                # Create JIRA ticket for APP issues
                if [ -s app_content.txt ]; then
                  echo "Sending APP dependency report to Jira..."

                  # Debug: check the content
                  echo "File size: $(wc -c app_content.txt)"
                  echo "First few characters:"
                  head -c 100 app_content.txt

                  # Prepare the payload by wrapping the content in the expected structure
                  jq -n --arg title "react-app NPM Dependency Report" \
                        --arg body "$(cat app_content.txt)" \
                        '{
                          "data": {
                            "title": $title,
                            "body": $body
                          }
                        }' > app_payload.json
                  
                  # Debug the final payload
                  echo "\nFinal payload structure:"
                  cat app_payload.json | jq '.'
                  
                  APP_RESPONSE=$(curl -X POST \
                    -H "Content-Type: application/json" \
                    -H "X-Automation-Webhook-Token: ${{ secrets.JIRA_API_TOKEN }}" \
                    --data @app_payload.json \
                    -w "\n%{http_code}" \
                    -s \
                    "${{ secrets.JIRA_WEBHOOK_URL }}")
                  
                  APP_HTTP_CODE=$(echo "$APP_RESPONSE" | tail -n1)
                  APP_CONTENT_RESPONSE=$(echo "$APP_RESPONSE" | sed '$d')
                  
                  echo "\nAPP Request Status Code: $APP_HTTP_CODE"
                  
                  if [ "$APP_HTTP_CODE" -ge 200 ] && [ "$APP_HTTP_CODE" -lt 300 ]; then
                    echo "✅ APP Jira ticket created successfully"
                  else
                    echo "❌ Failed to create APP Jira ticket. Status code: $APP_HTTP_CODE"
                    echo "Response: $APP_CONTENT_RESPONSE" 
                    exit 1
                  fi
                else
                  echo "No APP content found to send to Jira"
                fi
